<?php
namespace MageBackup\Aws\ElastiCache;

use MageBackup\Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon ElastiCache** service.
 *
 * @method \MageBackup\Aws\Result addTagsToResource(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise addTagsToResourceAsync(array $args = [])
 * @method \MageBackup\Aws\Result authorizeCacheSecurityGroupIngress(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise authorizeCacheSecurityGroupIngressAsync(array $args = [])
 * @method \MageBackup\Aws\Result copySnapshot(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise copySnapshotAsync(array $args = [])
 * @method \MageBackup\Aws\Result createCacheCluster(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createCacheClusterAsync(array $args = [])
 * @method \MageBackup\Aws\Result createCacheParameterGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createCacheParameterGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result createCacheSecurityGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createCacheSecurityGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result createCacheSubnetGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createCacheSubnetGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result createReplicationGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createReplicationGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result createSnapshot(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createSnapshotAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteCacheCluster(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteCacheClusterAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteCacheParameterGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteCacheParameterGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteCacheSecurityGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteCacheSecurityGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteCacheSubnetGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteCacheSubnetGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteReplicationGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteReplicationGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteSnapshot(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteSnapshotAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeCacheClusters(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeCacheClustersAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeCacheEngineVersions(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeCacheEngineVersionsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeCacheParameterGroups(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeCacheParameterGroupsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeCacheParameters(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeCacheParametersAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeCacheSecurityGroups(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeCacheSecurityGroupsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeCacheSubnetGroups(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeCacheSubnetGroupsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeEngineDefaultParameters(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeEngineDefaultParametersAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeEvents(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeEventsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeReplicationGroups(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeReplicationGroupsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeReservedCacheNodes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeReservedCacheNodesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeReservedCacheNodesOfferings(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeReservedCacheNodesOfferingsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeSnapshots(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeSnapshotsAsync(array $args = [])
 * @method \MageBackup\Aws\Result listAllowedNodeTypeModifications(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listAllowedNodeTypeModificationsAsync(array $args = [])
 * @method \MageBackup\Aws\Result listTagsForResource(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifyCacheCluster(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifyCacheClusterAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifyCacheParameterGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifyCacheParameterGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifyCacheSubnetGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifyCacheSubnetGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifyReplicationGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifyReplicationGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result purchaseReservedCacheNodesOffering(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise purchaseReservedCacheNodesOfferingAsync(array $args = [])
 * @method \MageBackup\Aws\Result rebootCacheCluster(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise rebootCacheClusterAsync(array $args = [])
 * @method \MageBackup\Aws\Result removeTagsFromResource(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise removeTagsFromResourceAsync(array $args = [])
 * @method \MageBackup\Aws\Result resetCacheParameterGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise resetCacheParameterGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result revokeCacheSecurityGroupIngress(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise revokeCacheSecurityGroupIngressAsync(array $args = [])
 */
class ElastiCacheClient extends AwsClient {}
