<script type="text/javascript">
    $J(function(){$J("#tabs").tabs();});
</script>
<?php $channels = $this->getSubscribedChannelsWithApi(); ?>
<?php if(count($channels) > 0): ?>
    <div id="tabs" style="width:800px;">
        <ul>
            <?php foreach($channels as $code => $label): ?>
                <li><a href="#tabs-<?php echo $code; ?>"><?php echo $label; ?></a></li>
            <?php endforeach; ?>
        </ul>
        <?php foreach($channels as $code => $label): ?>
            <div id="tabs-<?php echo $code; ?>">
                <?php echo $this->getLayout()->createBlock('Adminhtml/Widget_Container')->setTemplate('Mpm/Configuration/Webservices/'.$code.'.phtml')->toHtml(); ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif ?>