<?php if (!$this->getRule()->getIsSystem()): ?>

<div class="entry-edit">
<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Product matching to conditions'); ?></h4>
    <div class="form-buttons"></div>
</div>
<div class="fieldset fieldset-wide" id="products_content">
    <div class="hor-scroll">
        <?php echo $this->getGridParentHtml() ?>
    </div>
</div>
</div>

<?php endif; ?>