<?php
namespace MageBackup\Aws\AutoScaling;

use MageBackup\Aws\AwsClient;

/**
 * Auto Scaling client.
 *
 * @method \MageBackup\Aws\Result attachInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise attachInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result attachLoadBalancers(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise attachLoadBalancersAsync(array $args = [])
 * @method \MageBackup\Aws\Result completeLifecycleAction(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise completeLifecycleActionAsync(array $args = [])
 * @method \MageBackup\Aws\Result createAutoScalingGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createAutoScalingGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result createLaunchConfiguration(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createLaunchConfigurationAsync(array $args = [])
 * @method \MageBackup\Aws\Result createOrUpdateTags(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createOrUpdateTagsAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteAutoScalingGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteAutoScalingGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteLaunchConfiguration(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteLaunchConfigurationAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteLifecycleHook(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteLifecycleHookAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteNotificationConfiguration(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteNotificationConfigurationAsync(array $args = [])
 * @method \MageBackup\Aws\Result deletePolicy(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deletePolicyAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteScheduledAction(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteScheduledActionAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteTags(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteTagsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeAccountLimits(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeAccountLimitsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeAdjustmentTypes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeAdjustmentTypesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeAutoScalingGroups(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeAutoScalingGroupsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeAutoScalingInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeAutoScalingInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeAutoScalingNotificationTypes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeAutoScalingNotificationTypesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeLaunchConfigurations(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeLaunchConfigurationsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeLifecycleHookTypes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeLifecycleHookTypesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeLifecycleHooks(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeLifecycleHooksAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeLoadBalancers(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeLoadBalancersAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeMetricCollectionTypes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeMetricCollectionTypesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeNotificationConfigurations(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeNotificationConfigurationsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describePolicies(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describePoliciesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeScalingActivities(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeScalingActivitiesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeScalingProcessTypes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeScalingProcessTypesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeScheduledActions(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeScheduledActionsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeTags(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeTagsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeTerminationPolicyTypes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeTerminationPolicyTypesAsync(array $args = [])
 * @method \MageBackup\Aws\Result detachInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise detachInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result detachLoadBalancers(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise detachLoadBalancersAsync(array $args = [])
 * @method \MageBackup\Aws\Result disableMetricsCollection(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise disableMetricsCollectionAsync(array $args = [])
 * @method \MageBackup\Aws\Result enableMetricsCollection(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise enableMetricsCollectionAsync(array $args = [])
 * @method \MageBackup\Aws\Result enterStandby(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise enterStandbyAsync(array $args = [])
 * @method \MageBackup\Aws\Result executePolicy(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise executePolicyAsync(array $args = [])
 * @method \MageBackup\Aws\Result exitStandby(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise exitStandbyAsync(array $args = [])
 * @method \MageBackup\Aws\Result putLifecycleHook(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise putLifecycleHookAsync(array $args = [])
 * @method \MageBackup\Aws\Result putNotificationConfiguration(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise putNotificationConfigurationAsync(array $args = [])
 * @method \MageBackup\Aws\Result putScalingPolicy(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise putScalingPolicyAsync(array $args = [])
 * @method \MageBackup\Aws\Result putScheduledUpdateGroupAction(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise putScheduledUpdateGroupActionAsync(array $args = [])
 * @method \MageBackup\Aws\Result recordLifecycleActionHeartbeat(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise recordLifecycleActionHeartbeatAsync(array $args = [])
 * @method \MageBackup\Aws\Result resumeProcesses(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise resumeProcessesAsync(array $args = [])
 * @method \MageBackup\Aws\Result setDesiredCapacity(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise setDesiredCapacityAsync(array $args = [])
 * @method \MageBackup\Aws\Result setInstanceHealth(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise setInstanceHealthAsync(array $args = [])
 * @method \MageBackup\Aws\Result setInstanceProtection(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise setInstanceProtectionAsync(array $args = [])
 * @method \MageBackup\Aws\Result suspendProcesses(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise suspendProcessesAsync(array $args = [])
 * @method \MageBackup\Aws\Result terminateInstanceInAutoScalingGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise terminateInstanceInAutoScalingGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateAutoScalingGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateAutoScalingGroupAsync(array $args = [])
 */
class AutoScalingClient extends AwsClient {}
