<?php
namespace MageBackup\Aws\Ecs;

use MageBackup\Aws\AwsClient;

/**
 * This client is used to interact with **Amazon ECS**.
 *
 * @method \MageBackup\Aws\Result createCluster(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createClusterAsync(array $args = [])
 * @method \MageBackup\Aws\Result createService(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createServiceAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteCluster(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteClusterAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteService(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteServiceAsync(array $args = [])
 * @method \MageBackup\Aws\Result deregisterContainerInstance(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deregisterContainerInstanceAsync(array $args = [])
 * @method \MageBackup\Aws\Result deregisterTaskDefinition(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deregisterTaskDefinitionAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeClusters(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeClustersAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeContainerInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeContainerInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeServices(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeServicesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeTaskDefinition(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeTaskDefinitionAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeTasks(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeTasksAsync(array $args = [])
 * @method \MageBackup\Aws\Result discoverPollEndpoint(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise discoverPollEndpointAsync(array $args = [])
 * @method \MageBackup\Aws\Result listClusters(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listClustersAsync(array $args = [])
 * @method \MageBackup\Aws\Result listContainerInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listContainerInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result listServices(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listServicesAsync(array $args = [])
 * @method \MageBackup\Aws\Result listTaskDefinitionFamilies(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listTaskDefinitionFamiliesAsync(array $args = [])
 * @method \MageBackup\Aws\Result listTaskDefinitions(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listTaskDefinitionsAsync(array $args = [])
 * @method \MageBackup\Aws\Result listTasks(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listTasksAsync(array $args = [])
 * @method \MageBackup\Aws\Result registerContainerInstance(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise registerContainerInstanceAsync(array $args = [])
 * @method \MageBackup\Aws\Result registerTaskDefinition(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise registerTaskDefinitionAsync(array $args = [])
 * @method \MageBackup\Aws\Result runTask(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise runTaskAsync(array $args = [])
 * @method \MageBackup\Aws\Result startTask(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise startTaskAsync(array $args = [])
 * @method \MageBackup\Aws\Result stopTask(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise stopTaskAsync(array $args = [])
 * @method \MageBackup\Aws\Result submitContainerStateChange(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise submitContainerStateChangeAsync(array $args = [])
 * @method \MageBackup\Aws\Result submitTaskStateChange(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise submitTaskStateChangeAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateContainerAgent(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateContainerAgentAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateService(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateServiceAsync(array $args = [])
 */
class EcsClient extends AwsClient {}
