<?php

class TBT_Rewards_Helper_Metrics_Revenue_NonMembers extends TBT_Rewards_Helper_Metrics_Revenue
{
    /**
     * Overwrites parent method and calculates total revenue generated by non-members of the loyalty program
     * in the applied period.
     *
     * @param  array  $series
     * @return TBT_Rewards_Helper_Metrics_Revenue_NonMembers
     */
    protected function _prepareSeries($series = array())
    {
        if (is_null($series)) {
            return $this;
        }

        $nonMembersRevenue = 0;
        foreach ($series as $key => $value) {
            if (!$value['is_member']) {
                $nonMembersRevenue += $value['total_revenue_amount'];
            }
        }

        $nonMembersRevenue = $this->_formatContentAsCurrency($nonMembersRevenue);

        $this->addSeries(array(
            'title'   => 'Non Members Total Revenue',
            'content' => $nonMembersRevenue,
            // 'note' => ''
        ));

        return $this;
    }
}
