<div class="page-title">
    <h1>Request RMA</h1>
</div>
<form action="<?php echo $this->getStep1PostUrl()?>" method="POST" id="rma-form-validate" >
<div class='fieldset'>
    <h2 class="legend"><?php echo $this->__("Please, enter an your Order # and Email") ?></h2>
    <ul class="form-list">
        <li class="wide">
            <label for="order_increment_id" class="required"><em>*</em><?php echo $this->__("Order #") ?></label>
            <div class="input-box">
                <input type='text' name="order_increment_id" id='order_increment_id' class="required-entry" value="<?php echo $this->getOrderIncrementId()?>"/>
            </div>
        </li>
        <li class="wide">
            <label for="email" class="required"><em>*</em><?php echo $this->__("Email") ?></label>
            <div class="input-box">
                <input type='text' name="email" id='email' class="required-entry" value="<?php echo $this->getEmail()?>"/>
            </div>
        </li>
    </ul>
    <button type="submit" title="<?php echo $this->__("Next") ?>" class="button"><span><span><?php echo $this->__("Next") ?></span></span></button>
</div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('rma-form-validate', true);
//]]>
</script>