<?php
namespace MageBackup\Aws\DirectoryService;

use MageBackup\Aws\AwsClient;

/**
 * AWS Directory Service client
 *
 * @method \MageBackup\Aws\Result connectDirectory(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise connectDirectoryAsync(array $args = [])
 * @method \MageBackup\Aws\Result createAlias(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createAliasAsync(array $args = [])
 * @method \MageBackup\Aws\Result createComputer(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createComputerAsync(array $args = [])
 * @method \MageBackup\Aws\Result createConditionalForwarder(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createConditionalForwarderAsync(array $args = [])
 * @method \MageBackup\Aws\Result createDirectory(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createDirectoryAsync(array $args = [])
 * @method \MageBackup\Aws\Result createMicrosoftAD(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createMicrosoftADAsync(array $args = [])
 * @method \MageBackup\Aws\Result createSnapshot(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createSnapshotAsync(array $args = [])
 * @method \MageBackup\Aws\Result createTrust(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createTrustAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteConditionalForwarder(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteConditionalForwarderAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteDirectory(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteDirectoryAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteSnapshot(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteSnapshotAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteTrust(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteTrustAsync(array $args = [])
 * @method \MageBackup\Aws\Result deregisterEventTopic(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deregisterEventTopicAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeConditionalForwarders(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeConditionalForwardersAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeDirectories(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeDirectoriesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeEventTopics(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeEventTopicsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeSnapshots(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeSnapshotsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeTrusts(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeTrustsAsync(array $args = [])
 * @method \MageBackup\Aws\Result disableRadius(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise disableRadiusAsync(array $args = [])
 * @method \MageBackup\Aws\Result disableSso(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise disableSsoAsync(array $args = [])
 * @method \MageBackup\Aws\Result enableRadius(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise enableRadiusAsync(array $args = [])
 * @method \MageBackup\Aws\Result enableSso(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise enableSsoAsync(array $args = [])
 * @method \MageBackup\Aws\Result getDirectoryLimits(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise getDirectoryLimitsAsync(array $args = [])
 * @method \MageBackup\Aws\Result getSnapshotLimits(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise getSnapshotLimitsAsync(array $args = [])
 * @method \MageBackup\Aws\Result registerEventTopic(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise registerEventTopicAsync(array $args = [])
 * @method \MageBackup\Aws\Result restoreFromSnapshot(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise restoreFromSnapshotAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateConditionalForwarder(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateConditionalForwarderAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateRadius(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateRadiusAsync(array $args = [])
 * @method \MageBackup\Aws\Result verifyTrust(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise verifyTrustAsync(array $args = [])
 */
class DirectoryServiceClient extends AwsClient {}
