<?php $transfer = $this->getTransfer(); ?>

<?php if ($transfer->isOrder()): ?>       
    <a href="<?php echo $this->getOrderUrl($transfer->getReferenceId()) ?>">
            <?php echo $this->__('View Order') ?></a>

<?php elseif ($transfer->isReview()): ?>       
    <a href="<?php echo $this->getReviewUrl($transfer->getReferenceId()) ?>">
            <?php echo $this->__('View Review') ?></a>

<?php elseif ($transfer->isFriendTransfer()): ?>
    <?php $friend_email = $this->getCustomerEmail($transfer->getReferenceId()) ?>
    <a href="mailto:<?php echo $friend_email ?>">
            <?php echo $friend_email ?></a>
<?php endif ?>