<?php
namespace MageBackup\Aws\ElasticBeanstalk;

use MageBackup\Aws\AwsClient;

/**
 * This client is used to interact with the **AWS Elastic Beanstalk** service.
 *
 * @method \MageBackup\Aws\Result abortEnvironmentUpdate(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise abortEnvironmentUpdateAsync(array $args = [])
 * @method \MageBackup\Aws\Result applyEnvironmentManagedAction(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise applyEnvironmentManagedActionAsync(array $args = [])
 * @method \MageBackup\Aws\Result checkDNSAvailability(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise checkDNSAvailabilityAsync(array $args = [])
 * @method \MageBackup\Aws\Result composeEnvironments(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise composeEnvironmentsAsync(array $args = [])
 * @method \MageBackup\Aws\Result createApplication(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createApplicationAsync(array $args = [])
 * @method \MageBackup\Aws\Result createApplicationVersion(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createApplicationVersionAsync(array $args = [])
 * @method \MageBackup\Aws\Result createConfigurationTemplate(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createConfigurationTemplateAsync(array $args = [])
 * @method \MageBackup\Aws\Result createEnvironment(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createEnvironmentAsync(array $args = [])
 * @method \MageBackup\Aws\Result createStorageLocation(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createStorageLocationAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteApplication(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteApplicationAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteApplicationVersion(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteApplicationVersionAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteConfigurationTemplate(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteConfigurationTemplateAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteEnvironmentConfiguration(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteEnvironmentConfigurationAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeApplicationVersions(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeApplicationVersionsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeApplications(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeApplicationsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeConfigurationOptions(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeConfigurationOptionsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeConfigurationSettings(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeConfigurationSettingsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeEnvironmentHealth(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeEnvironmentHealthAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeEnvironmentManagedActionHistory(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeEnvironmentManagedActionHistoryAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeEnvironmentManagedActions(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeEnvironmentManagedActionsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeEnvironmentResources(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeEnvironmentResourcesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeEnvironments(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeEnvironmentsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeEvents(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeEventsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeInstancesHealth(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeInstancesHealthAsync(array $args = [])
 * @method \MageBackup\Aws\Result listAvailableSolutionStacks(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listAvailableSolutionStacksAsync(array $args = [])
 * @method \MageBackup\Aws\Result rebuildEnvironment(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise rebuildEnvironmentAsync(array $args = [])
 * @method \MageBackup\Aws\Result requestEnvironmentInfo(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise requestEnvironmentInfoAsync(array $args = [])
 * @method \MageBackup\Aws\Result restartAppServer(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise restartAppServerAsync(array $args = [])
 * @method \MageBackup\Aws\Result retrieveEnvironmentInfo(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise retrieveEnvironmentInfoAsync(array $args = [])
 * @method \MageBackup\Aws\Result swapEnvironmentCNAMEs(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise swapEnvironmentCNAMEsAsync(array $args = [])
 * @method \MageBackup\Aws\Result terminateEnvironment(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise terminateEnvironmentAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateApplication(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateApplicationAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateApplicationVersion(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateApplicationVersionAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateConfigurationTemplate(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateConfigurationTemplateAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateEnvironment(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateEnvironmentAsync(array $args = [])
 * @method \MageBackup\Aws\Result validateConfigurationSettings(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise validateConfigurationSettingsAsync(array $args = [])
 */
class ElasticBeanstalkClient extends AwsClient {}
