<?php
namespace MageBackup\Aws\Ec2;

use MageBackup\Aws\AwsClient;
use MageBackup\Aws\Api\Service;
use MageBackup\Aws\Api\DocModel;
use MageBackup\Aws\Api\ApiProvider;

/**
 * Client used to interact with Amazon EC2.
 *
 * @method \MageBackup\Aws\Result acceptVpcPeeringConnection(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise acceptVpcPeeringConnectionAsync(array $args = [])
 * @method \MageBackup\Aws\Result allocateAddress(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise allocateAddressAsync(array $args = [])
 * @method \MageBackup\Aws\Result allocateHosts(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise allocateHostsAsync(array $args = [])
 * @method \MageBackup\Aws\Result assignPrivateIpAddresses(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise assignPrivateIpAddressesAsync(array $args = [])
 * @method \MageBackup\Aws\Result associateAddress(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise associateAddressAsync(array $args = [])
 * @method \MageBackup\Aws\Result associateDhcpOptions(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise associateDhcpOptionsAsync(array $args = [])
 * @method \MageBackup\Aws\Result associateRouteTable(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise associateRouteTableAsync(array $args = [])
 * @method \MageBackup\Aws\Result attachClassicLinkVpc(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise attachClassicLinkVpcAsync(array $args = [])
 * @method \MageBackup\Aws\Result attachInternetGateway(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise attachInternetGatewayAsync(array $args = [])
 * @method \MageBackup\Aws\Result attachNetworkInterface(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise attachNetworkInterfaceAsync(array $args = [])
 * @method \MageBackup\Aws\Result attachVolume(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise attachVolumeAsync(array $args = [])
 * @method \MageBackup\Aws\Result attachVpnGateway(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise attachVpnGatewayAsync(array $args = [])
 * @method \MageBackup\Aws\Result authorizeSecurityGroupEgress(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise authorizeSecurityGroupEgressAsync(array $args = [])
 * @method \MageBackup\Aws\Result authorizeSecurityGroupIngress(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise authorizeSecurityGroupIngressAsync(array $args = [])
 * @method \MageBackup\Aws\Result bundleInstance(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise bundleInstanceAsync(array $args = [])
 * @method \MageBackup\Aws\Result cancelBundleTask(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise cancelBundleTaskAsync(array $args = [])
 * @method \MageBackup\Aws\Result cancelConversionTask(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise cancelConversionTaskAsync(array $args = [])
 * @method \MageBackup\Aws\Result cancelExportTask(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise cancelExportTaskAsync(array $args = [])
 * @method \MageBackup\Aws\Result cancelImportTask(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise cancelImportTaskAsync(array $args = [])
 * @method \MageBackup\Aws\Result cancelReservedInstancesListing(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise cancelReservedInstancesListingAsync(array $args = [])
 * @method \MageBackup\Aws\Result cancelSpotFleetRequests(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise cancelSpotFleetRequestsAsync(array $args = [])
 * @method \MageBackup\Aws\Result cancelSpotInstanceRequests(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise cancelSpotInstanceRequestsAsync(array $args = [])
 * @method \MageBackup\Aws\Result confirmProductInstance(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise confirmProductInstanceAsync(array $args = [])
 * @method \MageBackup\Aws\Result copyImage(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise copyImageAsync(array $args = [])
 * @method \MageBackup\Aws\Result copySnapshot(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise copySnapshotAsync(array $args = [])
 * @method \MageBackup\Aws\Result createCustomerGateway(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createCustomerGatewayAsync(array $args = [])
 * @method \MageBackup\Aws\Result createDhcpOptions(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createDhcpOptionsAsync(array $args = [])
 * @method \MageBackup\Aws\Result createFlowLogs(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createFlowLogsAsync(array $args = [])
 * @method \MageBackup\Aws\Result createImage(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createImageAsync(array $args = [])
 * @method \MageBackup\Aws\Result createInstanceExportTask(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createInstanceExportTaskAsync(array $args = [])
 * @method \MageBackup\Aws\Result createInternetGateway(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createInternetGatewayAsync(array $args = [])
 * @method \MageBackup\Aws\Result createKeyPair(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createKeyPairAsync(array $args = [])
 * @method \MageBackup\Aws\Result createNatGateway(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createNatGatewayAsync(array $args = [])
 * @method \MageBackup\Aws\Result createNetworkAcl(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createNetworkAclAsync(array $args = [])
 * @method \MageBackup\Aws\Result createNetworkAclEntry(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createNetworkAclEntryAsync(array $args = [])
 * @method \MageBackup\Aws\Result createNetworkInterface(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createNetworkInterfaceAsync(array $args = [])
 * @method \MageBackup\Aws\Result createPlacementGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createPlacementGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result createReservedInstancesListing(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createReservedInstancesListingAsync(array $args = [])
 * @method \MageBackup\Aws\Result createRoute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createRouteAsync(array $args = [])
 * @method \MageBackup\Aws\Result createRouteTable(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createRouteTableAsync(array $args = [])
 * @method \MageBackup\Aws\Result createSecurityGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createSecurityGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result createSnapshot(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createSnapshotAsync(array $args = [])
 * @method \MageBackup\Aws\Result createSpotDatafeedSubscription(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createSpotDatafeedSubscriptionAsync(array $args = [])
 * @method \MageBackup\Aws\Result createSubnet(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createSubnetAsync(array $args = [])
 * @method \MageBackup\Aws\Result createTags(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createTagsAsync(array $args = [])
 * @method \MageBackup\Aws\Result createVolume(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createVolumeAsync(array $args = [])
 * @method \MageBackup\Aws\Result createVpc(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createVpcAsync(array $args = [])
 * @method \MageBackup\Aws\Result createVpcEndpoint(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createVpcEndpointAsync(array $args = [])
 * @method \MageBackup\Aws\Result createVpcPeeringConnection(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createVpcPeeringConnectionAsync(array $args = [])
 * @method \MageBackup\Aws\Result createVpnConnection(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createVpnConnectionAsync(array $args = [])
 * @method \MageBackup\Aws\Result createVpnConnectionRoute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createVpnConnectionRouteAsync(array $args = [])
 * @method \MageBackup\Aws\Result createVpnGateway(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createVpnGatewayAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteCustomerGateway(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteCustomerGatewayAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteDhcpOptions(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteDhcpOptionsAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteFlowLogs(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteFlowLogsAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteInternetGateway(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteInternetGatewayAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteKeyPair(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteKeyPairAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteNatGateway(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteNatGatewayAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteNetworkAcl(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteNetworkAclAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteNetworkAclEntry(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteNetworkAclEntryAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteNetworkInterface(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteNetworkInterfaceAsync(array $args = [])
 * @method \MageBackup\Aws\Result deletePlacementGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deletePlacementGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteRoute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteRouteAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteRouteTable(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteRouteTableAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteSecurityGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteSecurityGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteSnapshot(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteSnapshotAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteSpotDatafeedSubscription(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteSpotDatafeedSubscriptionAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteSubnet(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteSubnetAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteTags(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteTagsAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteVolume(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteVolumeAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteVpc(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteVpcAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteVpcEndpoints(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteVpcEndpointsAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteVpcPeeringConnection(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteVpcPeeringConnectionAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteVpnConnection(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteVpnConnectionAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteVpnConnectionRoute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteVpnConnectionRouteAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteVpnGateway(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteVpnGatewayAsync(array $args = [])
 * @method \MageBackup\Aws\Result deregisterImage(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deregisterImageAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeAccountAttributes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeAccountAttributesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeAddresses(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeAddressesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeAvailabilityZones(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeAvailabilityZonesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeBundleTasks(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeBundleTasksAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeClassicLinkInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeClassicLinkInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeConversionTasks(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeConversionTasksAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeCustomerGateways(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeCustomerGatewaysAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeDhcpOptions(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeDhcpOptionsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeExportTasks(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeExportTasksAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeFlowLogs(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeFlowLogsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeHosts(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeHostsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeIdFormat(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeIdFormatAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeImageAttribute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeImageAttributeAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeImages(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeImagesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeImportImageTasks(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeImportImageTasksAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeImportSnapshotTasks(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeImportSnapshotTasksAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeInstanceAttribute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeInstanceAttributeAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeInstanceStatus(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeInstanceStatusAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeInternetGateways(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeInternetGatewaysAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeKeyPairs(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeKeyPairsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeMovingAddresses(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeMovingAddressesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeNatGateways(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeNatGatewaysAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeNetworkAcls(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeNetworkAclsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeNetworkInterfaceAttribute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeNetworkInterfaceAttributeAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeNetworkInterfaces(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeNetworkInterfacesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describePlacementGroups(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describePlacementGroupsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describePrefixLists(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describePrefixListsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeRegions(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeRegionsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeReservedInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeReservedInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeReservedInstancesListings(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeReservedInstancesListingsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeReservedInstancesModifications(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeReservedInstancesModificationsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeReservedInstancesOfferings(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeReservedInstancesOfferingsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeRouteTables(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeRouteTablesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeScheduledInstanceAvailability(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeScheduledInstanceAvailabilityAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeScheduledInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeScheduledInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeSecurityGroupReferences(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeSecurityGroupReferencesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeSecurityGroups(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeSecurityGroupsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeSnapshotAttribute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeSnapshotAttributeAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeSnapshots(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeSnapshotsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeSpotDatafeedSubscription(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeSpotDatafeedSubscriptionAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeSpotFleetInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeSpotFleetInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeSpotFleetRequestHistory(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeSpotFleetRequestHistoryAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeSpotFleetRequests(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeSpotFleetRequestsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeSpotInstanceRequests(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeSpotInstanceRequestsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeSpotPriceHistory(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeSpotPriceHistoryAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeStaleSecurityGroups(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeStaleSecurityGroupsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeSubnets(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeSubnetsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeTags(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeTagsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeVolumeAttribute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeVolumeAttributeAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeVolumeStatus(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeVolumeStatusAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeVolumes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeVolumesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeVpcAttribute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeVpcAttributeAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeVpcClassicLink(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeVpcClassicLinkAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeVpcClassicLinkDnsSupport(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeVpcClassicLinkDnsSupportAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeVpcEndpointServices(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeVpcEndpointServicesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeVpcEndpoints(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeVpcEndpointsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeVpcPeeringConnections(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeVpcPeeringConnectionsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeVpcs(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeVpcsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeVpnConnections(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeVpnConnectionsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeVpnGateways(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeVpnGatewaysAsync(array $args = [])
 * @method \MageBackup\Aws\Result detachClassicLinkVpc(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise detachClassicLinkVpcAsync(array $args = [])
 * @method \MageBackup\Aws\Result detachInternetGateway(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise detachInternetGatewayAsync(array $args = [])
 * @method \MageBackup\Aws\Result detachNetworkInterface(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise detachNetworkInterfaceAsync(array $args = [])
 * @method \MageBackup\Aws\Result detachVolume(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise detachVolumeAsync(array $args = [])
 * @method \MageBackup\Aws\Result detachVpnGateway(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise detachVpnGatewayAsync(array $args = [])
 * @method \MageBackup\Aws\Result disableVgwRoutePropagation(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise disableVgwRoutePropagationAsync(array $args = [])
 * @method \MageBackup\Aws\Result disableVpcClassicLink(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise disableVpcClassicLinkAsync(array $args = [])
 * @method \MageBackup\Aws\Result disableVpcClassicLinkDnsSupport(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise disableVpcClassicLinkDnsSupportAsync(array $args = [])
 * @method \MageBackup\Aws\Result disassociateAddress(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise disassociateAddressAsync(array $args = [])
 * @method \MageBackup\Aws\Result disassociateRouteTable(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise disassociateRouteTableAsync(array $args = [])
 * @method \MageBackup\Aws\Result enableVgwRoutePropagation(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise enableVgwRoutePropagationAsync(array $args = [])
 * @method \MageBackup\Aws\Result enableVolumeIO(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise enableVolumeIOAsync(array $args = [])
 * @method \MageBackup\Aws\Result enableVpcClassicLink(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise enableVpcClassicLinkAsync(array $args = [])
 * @method \MageBackup\Aws\Result enableVpcClassicLinkDnsSupport(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise enableVpcClassicLinkDnsSupportAsync(array $args = [])
 * @method \MageBackup\Aws\Result getConsoleOutput(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise getConsoleOutputAsync(array $args = [])
 * @method \MageBackup\Aws\Result getPasswordData(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise getPasswordDataAsync(array $args = [])
 * @method \MageBackup\Aws\Result importImage(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise importImageAsync(array $args = [])
 * @method \MageBackup\Aws\Result importInstance(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise importInstanceAsync(array $args = [])
 * @method \MageBackup\Aws\Result importKeyPair(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise importKeyPairAsync(array $args = [])
 * @method \MageBackup\Aws\Result importSnapshot(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise importSnapshotAsync(array $args = [])
 * @method \MageBackup\Aws\Result importVolume(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise importVolumeAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifyHosts(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifyHostsAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifyIdFormat(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifyIdFormatAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifyImageAttribute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifyImageAttributeAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifyInstanceAttribute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifyInstanceAttributeAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifyInstancePlacement(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifyInstancePlacementAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifyNetworkInterfaceAttribute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifyNetworkInterfaceAttributeAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifyReservedInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifyReservedInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifySnapshotAttribute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifySnapshotAttributeAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifySpotFleetRequest(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifySpotFleetRequestAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifySubnetAttribute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifySubnetAttributeAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifyVolumeAttribute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifyVolumeAttributeAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifyVpcAttribute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifyVpcAttributeAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifyVpcEndpoint(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifyVpcEndpointAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifyVpcPeeringConnectionOptions(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifyVpcPeeringConnectionOptionsAsync(array $args = [])
 * @method \MageBackup\Aws\Result monitorInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise monitorInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result moveAddressToVpc(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise moveAddressToVpcAsync(array $args = [])
 * @method \MageBackup\Aws\Result purchaseReservedInstancesOffering(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise purchaseReservedInstancesOfferingAsync(array $args = [])
 * @method \MageBackup\Aws\Result purchaseScheduledInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise purchaseScheduledInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result rebootInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise rebootInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result registerImage(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise registerImageAsync(array $args = [])
 * @method \MageBackup\Aws\Result rejectVpcPeeringConnection(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise rejectVpcPeeringConnectionAsync(array $args = [])
 * @method \MageBackup\Aws\Result releaseAddress(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise releaseAddressAsync(array $args = [])
 * @method \MageBackup\Aws\Result releaseHosts(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise releaseHostsAsync(array $args = [])
 * @method \MageBackup\Aws\Result replaceNetworkAclAssociation(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise replaceNetworkAclAssociationAsync(array $args = [])
 * @method \MageBackup\Aws\Result replaceNetworkAclEntry(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise replaceNetworkAclEntryAsync(array $args = [])
 * @method \MageBackup\Aws\Result replaceRoute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise replaceRouteAsync(array $args = [])
 * @method \MageBackup\Aws\Result replaceRouteTableAssociation(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise replaceRouteTableAssociationAsync(array $args = [])
 * @method \MageBackup\Aws\Result reportInstanceStatus(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise reportInstanceStatusAsync(array $args = [])
 * @method \MageBackup\Aws\Result requestSpotFleet(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise requestSpotFleetAsync(array $args = [])
 * @method \MageBackup\Aws\Result requestSpotInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise requestSpotInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result resetImageAttribute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise resetImageAttributeAsync(array $args = [])
 * @method \MageBackup\Aws\Result resetInstanceAttribute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise resetInstanceAttributeAsync(array $args = [])
 * @method \MageBackup\Aws\Result resetNetworkInterfaceAttribute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise resetNetworkInterfaceAttributeAsync(array $args = [])
 * @method \MageBackup\Aws\Result resetSnapshotAttribute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise resetSnapshotAttributeAsync(array $args = [])
 * @method \MageBackup\Aws\Result restoreAddressToClassic(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise restoreAddressToClassicAsync(array $args = [])
 * @method \MageBackup\Aws\Result revokeSecurityGroupEgress(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise revokeSecurityGroupEgressAsync(array $args = [])
 * @method \MageBackup\Aws\Result revokeSecurityGroupIngress(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise revokeSecurityGroupIngressAsync(array $args = [])
 * @method \MageBackup\Aws\Result runInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise runInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result runScheduledInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise runScheduledInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result startInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise startInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result stopInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise stopInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result terminateInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise terminateInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result unassignPrivateIpAddresses(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise unassignPrivateIpAddressesAsync(array $args = [])
 * @method \MageBackup\Aws\Result unmonitorInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise unmonitorInstancesAsync(array $args = [])
 */
class Ec2Client extends AwsClient
{
    public function __construct(array $args)
    {
        $args['with_resolved'] = function (array $args) {
            $this->getHandlerList()->appendInit(
                CopySnapshotMiddleware::wrap(
                    $this,
                    $args['endpoint_provider']
                ),
                'ec2.copy_snapshot'
            );
        };

        parent::__construct($args);
    }

    /**
     * @internal
     * @codeCoverageIgnore
     */
    public static function applyDocFilters(array $api, array $docs)
    {
        // Several copy snapshot parameters are optional.
        $docs['shapes']['String']['refs']['CopySnapshotRequest$PresignedUrl']
            = '<div class="alert alert-info">The SDK will compute this value '
            . 'for you on your behalf.</div>';
        $docs['shapes']['String']['refs']['CopySnapshotRequest$DestinationRegion']
            = '<div class="alert alert-info">The SDK will populate this '
            . 'parameter on your behalf using the configured region value of '
            . 'the client.</div>';

        return [
            new Service($api, ApiProvider::defaultProvider()),
            new DocModel($docs)
        ];
    }
}
