<tr>
	<td style="vertical-align: middle;" width="5%">
		<input name="shipping_method[<?php echo $this->getAddressId() ?>]" type="radio" 
			value="<?php echo $this->htmlEscape($this->getRate()->getCode()) ?>" 
			id="s_method_<?php echo $this->getAddressId() ?>_<?php echo $this->getRate()->getCode() ?>"
			<?php if($this->getRate()->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> 
			onchange="majFraisPort(<?php echo $this->getAddressId(); ?>, 
				'<?php echo $this->getRate()->getCode() ?>')"
		/>
	</td>
	<td class="logo-mode-livraison" style="vertical-align: top;" width="5%">
		<label for="s_method_<?php echo $this->getAddressId() ?>_<?php echo $this->getRate()->getCode() ?>">
			<img src="<?php echo $this->getSkinUrl($this->getPicture()) ?>" alt="<?php echo $this->getRate()->getCarrierTitle() ?>" />
		</label>
	</td>
	<td class="x-small-text" style="vertical-align: middle;">
		<label for="s_method_<?php echo $this->getAddressId() ?>_<?php echo $this->getRate()->getCode() ?>">
			<strong><?php echo $this->getRate()->getCarrierTitle() ?></strong><br />
		</label>
    </td>
</tr>
<tr><td colspan="3" align="left" class="x-small-text" style="text-align:justify;">
			<strong>
<?php if($this->getRate()->getPrice() == 0) :?>
	<?php echo $this->helper('sqlishipping')->__('Rate')?>: 	<span class="texte-rose"><?php echo $this->__('Free')?></span>
<?php else :?>
	<?php $_excl = $this->getShippingPrice($this->getAddress(), $this->getRate()->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
	<?php $_incl = $this->getShippingPrice($this->getAddress(), $this->getRate()->getPrice(), true); ?>
	<?php echo $this->helper('sqlishipping')->__('Rate')?>:
	<?php if ($this->helper('tax')->displayShippingPriceExcludingTax() || $this->getHasTax($this->getAddress(), $this->getRate()->getPrice(), true)): ?>
		<?php echo $_excl; ?> <?php echo $this->helper('tax')->__('Excl. Tax'); ?>
	<?php elseif ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
		<?php echo $_incl; ?> <?php echo $this->helper('tax')->__('Incl. Tax'); ?>
	<?php elseif ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
		<?php echo $_excl; ?> <?php echo $this->helper('tax')->__('Excl. Tax'); ?>
		(<?php echo $_incl; ?> <?php echo $this->helper('tax')->__('Incl. Tax'); ?>)
	<?php endif; ?>
<?php endif; ?>

<?php if($this->getRate()->getAmountBeforeDiscount() > 0 &&  $this->getRate()->getAmountBeforeDiscount() > $this->getRate()->getPrice()) :?>
	<?php $_exclAmountBeforeDiscount = $this->getShippingPriceBeforeDiscount($this->getAddress(), $this->getRate()->getAmountBeforeDiscount(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
	<?php $_inclAmountBeforeDiscount = $this->getShippingPriceBeforeDiscount($this->getAddress(), $this->getRate()->getAmountBeforeDiscount(), true); ?>
	<?php if ($this->helper('tax')->displayShippingPriceExcludingTax()): ?>
		<div class="prix-au-lieu-de">
			<span><?php echo $this->helper('sqlishipping')->__('instead of')?> </span><span class="prix-barre"><?php echo $_exclAmountBeforeDiscount; ?></span>
		</div>
	<?php elseif ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
		<div class="prix-au-lieu-de" >
			<span><?php echo $this->helper('sqlishipping')->__('instead of')?> </span><span class="prix-barre"><?php echo $_inclAmountBeforeDiscount; ?></span>
		</div>
	<?php elseif ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
		<div class="prix-au-lieu-de" >
			<span><?php echo $this->helper('sqlishipping')->__('instead of')?> </span><span class="prix-barre" style="float:left;"> <?php echo $_exclAmountBeforeDiscount; ?> <?php echo $this->__('Excl. Tax'); ?>
				(<?php echo $_inclAmountBeforeDiscount; ?> <?php echo $this->__('Incl. Tax'); ?>)
			</span>
		</div>
	<?php endif; ?>
<?php endif; ?>

				<br />
				<?php $delivery = $this->getDeliveryTimes()?>
				<?php if($delivery) :?>
					<?php echo $delivery ?>

				<?php endif;?>
			</strong>

			<?php if($this->getDescription()) :?>
					<?php echo $this->getDescription()?>

			<?php endif;?></td></tr>

	



