<?php
$store_id = Mage::app()->getStore()->getStoreId();
$config = Mage::getModel('autocompleteplus_autosuggest/config');
$uuid = $config->getUUID();
$query = htmlentities(Mage::app()->getRequest()->getParam('q'), ENT_QUOTES);
$match_value = '';

try{
    $formkey_html = $this->getBlockHtml('formkey');	// '<input name="form_key" type="hidden" value="E3rpphc1BL6zyTB3" />' 
    $pattern = '/.*form_key.*value=\"([^\"]+)\"/s';
    if (preg_match($pattern, $formkey_html, $match)){
        if ($match){
    	   $match_value = $match[1];
        }
    }
} catch (Exception $e){
    Mage::logException($e);
}

?>
<!-- <div id="isp_search_result_page"></div> -->

<script>
    var __isp_fulltext_search_obj = {
        uuid: "<?php echo $this->escapeHtml($config->getUUID()); ?>",
        store_id: <?php echo $this->escapeHtml($store_id); ?>,
        query: "<?php echo $this->escapeHtml($query); ?>",
		formkey: "<?php echo $this->escapeHtml($match_value); ?>"
    };
</script>
    <?php
        $helper = Mage::helper('autocompleteplus_autosuggest');
        $server_url = $helper->getServerUrl();
        $url = $server_url . '/ma_load_search_page?isp_platform=magento&r=002'; 
        $resp = $helper->sendCurl($url);
        $response_json = json_decode($resp);
        echo $response_json->html;
    ?>