<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?sensor=false"></script>
<?php
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, 'http://ws.colissimo.fr/supervision-wspudo/supervision.jsp');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    $contents = curl_exec ($ch);
    $_web_service_enable = 1;
    if(trim($contents) != "[OK]")
    {
        $_web_service_enable = 0;
    }

    curl_close ($ch);

    $customer_id = Mage::getSingleton('customer/session')->getCustomer()->getId();
    $model = Mage::getResourceSingleton('tatvashipping/tempcolissimowebservicedata')->deleteOldData($customer_id);
?>

<?php
    if($_web_service_enable != 0)
    {
        $address = $this->getAddress();
        $address_id = $address->getId();
        $street1 = $address->getStreet();
        $street = $street1[0];
        $postcode = $address->getPostcode();
        $city = $address->getCity();
        $countryName = Mage::getModel('directory/country')->load($address->getCountry())->getName();
        $weight = $address->getWeight();
        $shipping_date = date('d/m/Y');
        $shipping_method_id = 's_method_'.$address_id.'_colissimo_colissimo';

        //echo "<br/>"."postcode = ".$postcode."<br/>"."city = ".$city."<br/>"."street = ".$street."<br/>"."countryName = ".$countryName."<br/>"."weight = ".$weight."<br/>"."shipping_date = ".$shipping_date;

        $params = array(
                    'accountNumber'     => Mage::getStoreConfig('tatvasettings/tatva_settings/account'),
                    'password'          => Mage::getStoreConfig('tatvasettings/tatva_settings/password'),
                    'address'           => $street,
                    'zipCode'           => $postcode,
                    'city'              => $city,
                    'weight'            => $weight*1000,
                    'shippingDate'      => $shipping_date,
                    'filterRelay'       => '1',
                    'requestId '        => '1234567890ABCDEFGHIJ1234567890',
                );

        $model = Mage::getModel('tatvashipping/tempcolissimowebservicedata')->getWebserviceData($params);
        $rdv = Mage::getModel('tatvashipping/tempcolissimowebservicedata')->getWebserviceRdvData($params);
    }
?>
<script type="text/javascript">
   document.getElementById('shipping_method_name').value = '<?php echo $shipping_method_id;?>';
</script>
<?php if (!($_shippingRateGroups = $this->getShippingRates())): ?>
    <p><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>
<?php else: ?>
    <dl class="sp-methods">
    <?php $shippingCodePrice = array(); ?>
    <?php $_sole = count($_shippingRateGroups) == 1; foreach ($_shippingRateGroups as $code => $_rates): ?>
        <?php
            if($code == 'colissimo')
            {
                $enable = 1;
                $allowspecific = Mage::getStoreConfig('carriers/'.$code.'/sallowspecific');

                if($allowspecific == 1)
                {
                    $countrylist = Mage::getStoreConfig('carriers/'.$code.'/specificcountry');
                    if($_rate->getAddress()->getRegionCode() == 'GP' || $_rate->getAddress()->getRegionCode() == 'MQ' || $_rate->getAddress()->getRegionCode() == 'GF' || $_rate->getAddress()->getRegionCode() == 'RE' || $_rate->getAddress()->getRegionCode() == 'PM' || $_rate->getAddress()->getRegionCode() == 'YT' || $_rate->getAddress()->getRegionCode() == 'TF' || $_rate->getAddress()->getRegionCode() == 'WF' || $_rate->getAddress()->getRegionCode() == 'PF' || $_rate->getAddress()->getRegionCode() == 'NC' || $_rate->getAddress()->getRegionCode() == 'MC')
                    {
                       if(!strpos($countrylist,$_rate->getAddress()->getRegionCode()))
                       {
                            $enable = 0;
                       }
                    }

                }
                if($enable == 1)
                {
        ?>
                    <dt><?php echo $this->getCarrierName($code) ?></dt>
                    <dd>
                        <ul>
                        <?php $_sole = $_sole && count($_rates) == 1; foreach ($_rates as $_rate): ?>
                            <?php $shippingCodePrice[] = "'".$_rate->getCode()."':".(float)$_rate->getPrice(); ?>
                            <li>
                               <?php if ($_rate->getErrorMessage()):  ?>
                                <ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
                               <?php else: ?>
                                    <input name="shipping_method" type="radio" value="<?php echo $this->htmlEscape($_rate->getCode()) ?>" id="s_method_<?php echo $this->getAddress()->getId() ?>_<?php echo $_rate->getCode() ?>" class="radio"/>
                                    &nbsp;
                                    <img src="<?php echo $this->getSkinUrl(Mage::getModel('tatvashipping/carrier_'.$code)->getPicture()) ?>" alt="" />
                                    &nbsp;

                                    <?php if ($_rate->getCode() === $this->getAddressShippingMethod()): ?>
                                    <script type="text/javascript">
                                        //<![CDATA[
                                            lastPrice = <?php echo (float)$_rate->getPrice(); ?>;
                                        //]]>
                                    </script>
                                    <?php endif; ?>
                                    <label for="s_method_<?php echo $_rate->getCode() ?>" style="position: relative; top: 4px; vertical-align: text-bottom;"><?php echo $_rate->getMethodTitle() ?>
                                    <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                    <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                    <?php echo $_excl; ?>
                                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                    <?php endif; ?>
                                    </label>

                                    <?php
                                        if(($_rate->getAddress()->getCountry() == 'FR' && ($_rate->getAddress()->getRegionCode() != 'GP' && $_rate->getAddress()->getRegionCode() != 'MQ' && $_rate->getAddress()->getRegionCode() != 'GF' && $_rate->getAddress()->getRegionCode() != 'RE' && $_rate->getAddress()->getRegionCode() != 'PM' && $_rate->getAddress()->getRegionCode() != 'YT' && $_rate->getAddress()->getRegionCode() != 'TF' && $_rate->getAddress()->getRegionCode() != 'WF' && $_rate->getAddress()->getRegionCode() != 'PF' && $_rate->getAddress()->getRegionCode() != 'NC')) || $_rate->getAddress()->getCountry() == 'AD')
                                        {
                                            echo "<img src='".$this->getSkinUrl('images/tatva/socol_picto.png')."' style='"."padding: 3px 245px 0 0;float: right;"."' />";
                                        }
                                        if($_rate->getAddress()->getRegionCode() == 'GP' || $_rate->getAddress()->getRegionCode() == 'MQ' || $_rate->getAddress()->getRegionCode() == 'GF' || $_rate->getAddress()->getRegionCode() == 'RE' || $_rate->getAddress()->getRegionCode() == 'PM' || $_rate->getAddress()->getRegionCode() == 'YT' || $_rate->getAddress()->getRegionCode() == 'TF' || $_rate->getAddress()->getRegionCode() == 'WF' || $_rate->getAddress()->getRegionCode() == 'PF' || $_rate->getAddress()->getRegionCode() == 'NC' || $_rate->getAddress()->getRegionCode() == 'MC')
                                        {
                                            $country = $_rate->getAddress()->getRegionCode();
                                        }
                                        else
                                        {
                                            $country = $_rate->getAddress()->getCountry();
                                        }

                                    ?>
                               <?php endif; ?>
                            </li>
                        <?php endforeach; ?>
                        </ul>
                        <ul>
                            <li>
                                <?php
                                    $delivery = Mage::getModel('tatvashipping/carrier_colissimo')->getDeliveryTimes($country,'carriers/colissimo/delivery_text');
          						    if($delivery)
                                      {
                                          echo $delivery;
                                      }
                                      if(Mage::getStoreConfig('carriers/'.$code.'/description') != '')
                                      {
                                          echo "&nbsp;".Mage::getStoreConfig('carriers/'.$code.'/description');
                                      }
                                ?>
                            </li>
                        </ul>
                    </dd>
        <?php
                }
            }
            elseif($code == 'colissimopostoffice' || $code == 'colissimocityssimo' || $code == 'colissimolocalstore' )
            {
                if($this->helper('customer')->isLoggedIn())
                {
                    if($_web_service_enable != 0)
                    {
                        $enable = 1;
                        $allowspecific = Mage::getStoreConfig('carriers/'.$code.'/sallowspecific');

                        if($allowspecific == 1)
                        {
                            $countrylist = Mage::getStoreConfig('carriers/'.$code.'/specificcountry');
                            if($_rate->getAddress()->getRegionCode() == 'GP' || $_rate->getAddress()->getRegionCode() == 'MQ' || $_rate->getAddress()->getRegionCode() == 'GF' || $_rate->getAddress()->getRegionCode() == 'RE' || $_rate->getAddress()->getRegionCode() == 'PM' || $_rate->getAddress()->getRegionCode() == 'YT' || $_rate->getAddress()->getRegionCode() == 'TF' || $_rate->getAddress()->getRegionCode() == 'WF' || $_rate->getAddress()->getRegionCode() == 'PF' || $_rate->getAddress()->getRegionCode() == 'NC' || $_rate->getAddress()->getRegionCode() == 'MC')
                            {
                               if(!strpos($countrylist,$_rate->getAddress()->getRegionCode()))
                               {
                                    $enable = 0;
                               }
                            }

                        }
                        if($_rate->getAddress()->getPostcode() == 13128 || $_rate->getAddress()->getPostcode() == 13998 || $_rate->getAddress()->getPostcode() == 29240 || $_rate->getAddress()->getPostcode() == 30998 || $_rate->getAddress()->getPostcode() == 31998 ||  $_rate->getAddress()->getPostcode() == 33998 || $_rate->getAddress()->getPostcode() == 35998 || $_rate->getAddress()->getPostcode() == 45998 || $_rate->getAddress()->getPostcode() == 50115 || $_rate->getAddress()->getPostcode() == 56998 || $_rate->getAddress()->getPostcode() == 57998 || $_rate->getAddress()->getPostcode() == 59998 || $_rate->getAddress()->getPostcode() == 69998 || $_rate->getAddress()->getPostcode() == 83800 || $_rate->getAddress()->getPostcode() == 83998 || $_rate->getAddress()->getPostcode() == 13128 || $_rate->getAddress()->getPostcode() == 87998 || substr($_rate->getAddress()->getPostcode(),0,2) == 20)
                        {
                            $enable = 0;
                        }
                        if($enable == 1)
                        {
        ?>
                            <dt><?php echo $this->getCarrierName($code) ?></dt>
                            <dd>
                                <ul>
                                <?php $_sole = $_sole && count($_rates) == 1; foreach ($_rates as $_rate): ?>
                                    <?php $shippingCodePrice[] = "'".$_rate->getCode()."':".(float)$_rate->getPrice(); ?>
                                    <li>
                                       <?php if ($_rate->getErrorMessage()):  ?>
                                        <ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
                                       <?php else: ?>
                                            <input name="shipping_method" type="radio" value="<?php echo $this->htmlEscape($_rate->getCode()) ?>" id="s_method_<?php echo $this->getAddress()->getId() ?>_<?php echo $_rate->getCode() ?>" class="radio"
                                                onclick="<?php echo "openchoicepopup('popin1','".$_rate->getCode()."',0)"; ?>" />
                                            &nbsp;
                                            <img src="<?php echo $this->getSkinUrl(Mage::getModel('tatvashipping/carrier_'.$code)->getPicture()) ?>" alt="" />
                                            &nbsp;

                                            <?php if ($_rate->getCode() === $this->getAddressShippingMethod()): ?>
                                            <script type="text/javascript">
                                                //<![CDATA[
                                                    lastPrice = <?php echo (float)$_rate->getPrice(); ?>;
                                                //]]>
                                            </script>
                                            <?php endif; ?>
                                            <label for="s_method_<?php echo $_rate->getCode() ?>" style="position: relative; top: 4px; vertical-align: text-bottom;"><?php echo $_rate->getMethodTitle() ?>
                                            <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                            <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                            <?php echo $_excl; ?>
                                            <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                                (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                            <?php endif; ?>
                                            </label>

                                            <?php
                                                if(($_rate->getAddress()->getCountry() == 'FR' && ($_rate->getAddress()->getRegionCode() != 'GP' && $_rate->getAddress()->getRegionCode() != 'MQ' && $_rate->getAddress()->getRegionCode() != 'GF' && $_rate->getAddress()->getRegionCode() != 'RE' && $_rate->getAddress()->getRegionCode() != 'PM' && $_rate->getAddress()->getRegionCode() != 'YT' && $_rate->getAddress()->getRegionCode() != 'TF' && $_rate->getAddress()->getRegionCode() != 'WF' && $_rate->getAddress()->getRegionCode() != 'PF' && $_rate->getAddress()->getRegionCode() != 'NC')) || $_rate->getAddress()->getCountry() == 'AD')
                                                {
                                                    echo "<img src='".$this->getSkinUrl('images/tatva/socol_picto.png')."' style='"."padding: 3px 245px 0 0;float: right;"."' />";
                                                }
                                                if($_rate->getAddress()->getRegionCode() == 'GP' || $_rate->getAddress()->getRegionCode() == 'MQ' || $_rate->getAddress()->getRegionCode() == 'GF' || $_rate->getAddress()->getRegionCode() == 'RE' || $_rate->getAddress()->getRegionCode() == 'PM' || $_rate->getAddress()->getRegionCode() == 'YT' || $_rate->getAddress()->getRegionCode() == 'TF' || $_rate->getAddress()->getRegionCode() == 'WF' || $_rate->getAddress()->getRegionCode() == 'PF' || $_rate->getAddress()->getRegionCode() == 'NC' || $_rate->getAddress()->getRegionCode() == 'MC')
                                                {
                                                    $country = $_rate->getAddress()->getRegionCode();
                                                }
                                                else
                                                {
                                                    $country = $_rate->getAddress()->getCountry();
                                                }

                                            ?>
                                       <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                                </ul>
                                <ul>
                                    <li>
                                        <?php
                                            $delivery = Mage::getModel('tatvashipping/carrier_colissimo')->getDeliveryTimes($country,'carriers/colissimo/delivery_text');
                						    if($delivery)
                                            {
                                                echo $delivery;
                                            }
                                            if(Mage::getStoreConfig('carriers/'.$code.'/description') != '')
                                            {
                                                echo "&nbsp;".Mage::getStoreConfig('carriers/'.$code.'/description');
                                            }
                                        ?>
                                    </li>
                                </ul>
                            </dd>
        <?php
                        }
                    }
                }
            }
            elseif($code == 'colissimoappointment')
            {
                if($this->helper('customer')->isLoggedIn())
                {
                    if($rdv == 1)
                    {
                        $enable = 1;
                        $allowspecific = Mage::getStoreConfig('carriers/'.$code.'/sallowspecific');

                        if($allowspecific == 1)
                        {
                            $countrylist = Mage::getStoreConfig('carriers/'.$code.'/specificcountry');
                            if($_rate->getAddress()->getRegionCode() == 'GP' || $_rate->getAddress()->getRegionCode() == 'MQ' || $_rate->getAddress()->getRegionCode() == 'GF' || $_rate->getAddress()->getRegionCode() == 'RE' || $_rate->getAddress()->getRegionCode() == 'PM' || $_rate->getAddress()->getRegionCode() == 'YT' || $_rate->getAddress()->getRegionCode() == 'TF' || $_rate->getAddress()->getRegionCode() == 'WF' || $_rate->getAddress()->getRegionCode() == 'PF' || $_rate->getAddress()->getRegionCode() == 'NC' || $_rate->getAddress()->getRegionCode() == 'MC')
                            {
                               if(!strpos($countrylist,$_rate->getAddress()->getRegionCode()))
                               {
                                    $enable = 0;
                               }
                            }

                        }
                        if($enable == 1)
                        {
        ?>
                            <dt><?php echo $this->getCarrierName($code) ?></dt>
                            <dd>
                                <ul>
                                <?php $_sole = $_sole && count($_rates) == 1; foreach ($_rates as $_rate): ?>
                                    <?php $shippingCodePrice[] = "'".$_rate->getCode()."':".(float)$_rate->getPrice(); ?>
                                    <li>
                                       <?php if ($_rate->getErrorMessage()):  ?>
                                        <ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
                                       <?php else: ?>
                                            <input name="shipping_method" type="radio" value="<?php echo $this->htmlEscape($_rate->getCode()) ?>" id="s_method_<?php echo $this->getAddress()->getId() ?>_<?php echo $_rate->getCode() ?>" class="radio"
                                                onclick="afficherPopin3('popin3')" />
                                            &nbsp;
                                            <img src="<?php echo $this->getSkinUrl(Mage::getModel('tatvashipping/carrier_'.$code)->getPicture()) ?>" alt="" />
                                            &nbsp;

                                            <?php if ($_rate->getCode() === $this->getAddressShippingMethod()): ?>
                                            <script type="text/javascript">
                                                //<![CDATA[
                                                    lastPrice = <?php echo (float)$_rate->getPrice(); ?>;
                                                //]]>
                                            </script>
                                            <?php endif; ?>
                                            <label for="s_method_<?php echo $_rate->getCode() ?>" style="position: relative; top: 4px; vertical-align: text-bottom;"><?php echo $_rate->getMethodTitle() ?>
                                            <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                            <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                            <?php echo $_excl; ?>
                                            <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                                (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                            <?php endif; ?>
                                            </label>

                                            <?php
                                                if(($_rate->getAddress()->getCountry() == 'FR' && ($_rate->getAddress()->getRegionCode() != 'GP' && $_rate->getAddress()->getRegionCode() != 'MQ' && $_rate->getAddress()->getRegionCode() != 'GF' && $_rate->getAddress()->getRegionCode() != 'RE' && $_rate->getAddress()->getRegionCode() != 'PM' && $_rate->getAddress()->getRegionCode() != 'YT' && $_rate->getAddress()->getRegionCode() != 'TF' && $_rate->getAddress()->getRegionCode() != 'WF' && $_rate->getAddress()->getRegionCode() != 'PF' && $_rate->getAddress()->getRegionCode() != 'NC')) || $_rate->getAddress()->getCountry() == 'AD')
                                                {
                                                    echo "<img src='".$this->getSkinUrl('images/tatva/socol_picto.png')."' style='"."padding: 3px 245px 0 0;float: right;"."' />";
                                                }
                                                if($_rate->getAddress()->getRegionCode() == 'GP' || $_rate->getAddress()->getRegionCode() == 'MQ' || $_rate->getAddress()->getRegionCode() == 'GF' || $_rate->getAddress()->getRegionCode() == 'RE' || $_rate->getAddress()->getRegionCode() == 'PM' || $_rate->getAddress()->getRegionCode() == 'YT' || $_rate->getAddress()->getRegionCode() == 'TF' || $_rate->getAddress()->getRegionCode() == 'WF' || $_rate->getAddress()->getRegionCode() == 'PF' || $_rate->getAddress()->getRegionCode() == 'NC' || $_rate->getAddress()->getRegionCode() == 'MC')
                                                {
                                                    $country = $_rate->getAddress()->getRegionCode();
                                                }
                                                else
                                                {
                                                    $country = $_rate->getAddress()->getCountry();
                                                }
                                            ?>
                                       <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                                </ul>
                                <ul>
                                    <li>
                                        <?php
                                            $delivery = Mage::getModel('tatvashipping/carrier_colissimo')->getDeliveryTimes($country,'carriers/colissimo/delivery_text');
                						    if($delivery)
                                            {
                                                echo $delivery;
                                            }
                                            if(Mage::getStoreConfig('carriers/'.$code.'/description') != '')
                                            {
                                                echo "&nbsp;".Mage::getStoreConfig('carriers/'.$code.'/description');
                                            }
                                        ?>
                                    </li>
                                </ul>
                            </dd>
        <?php
                        }
                    }
                }
            }
            else
            {
        ?>
                <dt><?php echo $this->getCarrierName($code) ?></dt>
                <dd>
                    <ul>
                    <?php $_sole = $_sole && count($_rates) == 1; foreach ($_rates as $_rate): ?>
                        <?php $shippingCodePrice[] = "'".$_rate->getCode()."':".(float)$_rate->getPrice(); ?>
                        <li>
                           <?php if ($_rate->getErrorMessage()): ?>
                            <ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
                           <?php else: ?>
                                <?php if ($_sole) : ?>
                                <span class="no-display"><input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked" /></span>
                                <?php else: ?>
                                <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio"/>

                                <?php if ($_rate->getCode() === $this->getAddressShippingMethod()): ?>
                                <script type="text/javascript">
                                    //<![CDATA[
                                        lastPrice = <?php echo (float)$_rate->getPrice(); ?>;
                                    //]]>
                                </script>
                                <?php endif; ?>

                                <?php endif; ?>
                                <label for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $_rate->getMethodTitle() ?>
                                <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                <?php echo $_excl; ?>
                                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                <?php endif; ?>
                                </label>
                           <?php endif ?>
                        </li>
                    <?php endforeach; ?>
                    </ul>
                </dd>
        <?php
            }
        ?>
    <?php endforeach; ?>
    </dl>
    <input type="hidden" name="mobile_phone_no" id="mobile_phone_no" value="<?php echo $this->getAddress()->getMobilephone();?>" />
<script type="text/javascript">
//<![CDATA[
    <?php if (!empty($shippingCodePrice)): ?>
        var shippingCodePrice = {<?php echo implode(',',$shippingCodePrice); ?>};
    <?php endif; ?>

    $$('input[type="radio"][name="shipping_method"]').each(function(el){
        Event.observe(el, 'click', function(){
            if (el.checked == true) {
                var getShippingCode = el.getValue();
                <?php if (!empty($shippingCodePrice)): ?>
                    var newPrice = shippingCodePrice[getShippingCode];
                    if (!lastPrice) {
                        lastPrice = newPrice;
                        quoteBaseGrandTotal += newPrice;
                    }
                    if (newPrice != lastPrice) {
                        quoteBaseGrandTotal += (newPrice-lastPrice);
                        lastPrice = newPrice;
                    }
                <?php endif; ?>
                checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
                return false;
            }
       });
    });
//]]>
</script>
<?php endif; ?>

<script type="text/javascript" language="javascript">

    var customForm = new VarienForm('appointment_form',true);

    function afficherPopin3(idPopin)
    {
        
        document.getElementById('tatva_mobile_phone').value = document.getElementById('mobile_phone_no').value;
	    document.getElementById(idPopin).style.display="block";
	    return false;
    }

    function afficherPopin(idPopin)
    {
	    document.getElementById(idPopin).style.display="block";
	    return false;
    }

    function cacherPopin(idPopin)
    {
	    document.getElementById(idPopin).style.display="none";
	    return false;
    }

    function openchoicepopupmodify(idPopin,modify)
    {
	    cacherPopin('popin2');
        code = document.getElementById("selected_ship_method").value;
	    openchoicepopup(idPopin,code,modify);
    }

    function openchoicepopup(idPopin,code,modify)
    {
        jQuery("#popinloadingimg").css("display","block");
        var reloadurl = '<?php echo $this->getUrl('checkout/onepage/tatvachoicepopup/') ?>';
        jQuery.ajax({
            url: reloadurl,
            data: 'shipping_method='+code+'&modify='+modify,
	        type: "GET",
	        success: function(string, variable)
            {
                document.getElementById(idPopin).style.display="block";
                jQuery('#popinloadingimg').css("display","none");
                jQuery('#popin1').html(string);

	        }
        });

    }

    function test(search_button)
    {
        if(search_button == 1)
    	{
    	   document.getElementById('txtsearch').value = 1;

        }
        var address1 = document.getElementById('shipaddress').value;
        var city = document.getElementById('shipcity').value;
        var postcode = document.getElementById('shippostcode').value;
        if(postcode == "")
        {
          alert("<?php echo $this->__('Please insert zipcode.') ?>");
          return false;
        }
        if(city == "")
        {
          alert("<?php echo $this->__('Please insert city.') ?>");
          return false;
        }

        var ship_local_code = document.getElementById('chklocalstore').checked;
        var ship_post_code = document.getElementById('chkpostoffice').checked;
        var ship_cityssimo_code = document.getElementById('chkcityssimo').checked;
        var chk_mobility = document.getElementById('chkmobility').checked;

        var reloadurl = '<?php echo $this->getUrl('checkout/onepage/socollisimopopup/') ?>';
        jQuery.ajax({
            url: reloadurl,
            data: 'address='+address1+'&city='+city+'&postcode='+postcode+'&local='+ship_local_code+'&postoffice='+ship_post_code+'&cityssimo='+ship_cityssimo_code+'&mobility='+chk_mobility+'&search='+search_button+'&searchdata='+document.getElementById('txtsearch').value,
	        type: "GET",
	        success: function(string, variable)
            {
                jQuery('#ResponseDiv').html(string);
        	}
        });
    }

    function closepopup(idPopin,shipping_method_id)
    {
        document.getElementById(idPopin).style.display="none";
        document.getElementById(shipping_method_id).checked = "checked";
        return false;
    }

</script>
