

<script type="text/javascript">

    var CAPTION_POINT = '<?php echo $this->__('Points'); ?>';
    var CAPTION_POINTS = '<?php echo $this->__('Points'); ?>';
    var CAPTION_YOU_WILL_SPEND = '<?php echo $this->__('You Will Spend'); ?>';
    var CAPTION_WITH = '<?php echo $this->__('with'); ?>';
    var CAPTION_CANNOT_USE_POINTS = "<?php echo $this->__("You cannot use points until you login or create a new account.") ?>";
    var CAPTION_NOT_ENOUGH_POINTS = "<?php echo $this->__("You don't have enough points to use this redemption rule.") ?>";
    var CAPTION_REFRESHING_CART = '<?php echo $this->__("Refreshing cart, please wait..") ?>';

</script>