<?php
namespace MageBackup\Aws\DatabaseMigrationService;

use MageBackup\Aws\AwsClient;

/**
 * This client is used to interact with the **AWS Database Migration Service** service.
 * @method \MageBackup\Aws\Result addTagsToResource(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise addTagsToResourceAsync(array $args = [])
 * @method \MageBackup\Aws\Result createEndpoint(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createEndpointAsync(array $args = [])
 * @method \MageBackup\Aws\Result createReplicationInstance(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createReplicationInstanceAsync(array $args = [])
 * @method \MageBackup\Aws\Result createReplicationSubnetGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createReplicationSubnetGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result createReplicationTask(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createReplicationTaskAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteEndpoint(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteEndpointAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteReplicationInstance(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteReplicationInstanceAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteReplicationSubnetGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteReplicationSubnetGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteReplicationTask(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteReplicationTaskAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeAccountAttributes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeAccountAttributesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeConnections(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeConnectionsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeEndpointTypes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeEndpointTypesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeEndpoints(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeEndpointsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeOrderableReplicationInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeOrderableReplicationInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeRefreshSchemasStatus(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeRefreshSchemasStatusAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeReplicationInstances(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeReplicationInstancesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeReplicationSubnetGroups(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeReplicationSubnetGroupsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeReplicationTasks(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeReplicationTasksAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeSchemas(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeSchemasAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeTableStatistics(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeTableStatisticsAsync(array $args = [])
 * @method \MageBackup\Aws\Result listTagsForResource(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifyEndpoint(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifyEndpointAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifyReplicationInstance(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifyReplicationInstanceAsync(array $args = [])
 * @method \MageBackup\Aws\Result modifyReplicationSubnetGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise modifyReplicationSubnetGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result refreshSchemas(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise refreshSchemasAsync(array $args = [])
 * @method \MageBackup\Aws\Result removeTagsFromResource(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise removeTagsFromResourceAsync(array $args = [])
 * @method \MageBackup\Aws\Result startReplicationTask(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise startReplicationTaskAsync(array $args = [])
 * @method \MageBackup\Aws\Result stopReplicationTask(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise stopReplicationTaskAsync(array $args = [])
 * @method \MageBackup\Aws\Result testConnection(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise testConnectionAsync(array $args = [])
 */
class DatabaseMigrationServiceClient extends AwsClient {}
