<?php
namespace MageBackup\Aws\Sns;

use MageBackup\Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon Simple Notification Service (Amazon SNS)**.
 *
 * @method \MageBackup\Aws\Result addPermission(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise addPermissionAsync(array $args = [])
 * @method \MageBackup\Aws\Result confirmSubscription(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise confirmSubscriptionAsync(array $args = [])
 * @method \MageBackup\Aws\Result createPlatformApplication(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createPlatformApplicationAsync(array $args = [])
 * @method \MageBackup\Aws\Result createPlatformEndpoint(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createPlatformEndpointAsync(array $args = [])
 * @method \MageBackup\Aws\Result createTopic(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createTopicAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteEndpoint(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteEndpointAsync(array $args = [])
 * @method \MageBackup\Aws\Result deletePlatformApplication(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deletePlatformApplicationAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteTopic(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteTopicAsync(array $args = [])
 * @method \MageBackup\Aws\Result getEndpointAttributes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise getEndpointAttributesAsync(array $args = [])
 * @method \MageBackup\Aws\Result getPlatformApplicationAttributes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise getPlatformApplicationAttributesAsync(array $args = [])
 * @method \MageBackup\Aws\Result getSubscriptionAttributes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise getSubscriptionAttributesAsync(array $args = [])
 * @method \MageBackup\Aws\Result getTopicAttributes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise getTopicAttributesAsync(array $args = [])
 * @method \MageBackup\Aws\Result listEndpointsByPlatformApplication(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listEndpointsByPlatformApplicationAsync(array $args = [])
 * @method \MageBackup\Aws\Result listPlatformApplications(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listPlatformApplicationsAsync(array $args = [])
 * @method \MageBackup\Aws\Result listSubscriptions(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listSubscriptionsAsync(array $args = [])
 * @method \MageBackup\Aws\Result listSubscriptionsByTopic(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listSubscriptionsByTopicAsync(array $args = [])
 * @method \MageBackup\Aws\Result listTopics(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listTopicsAsync(array $args = [])
 * @method \MageBackup\Aws\Result publish(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise publishAsync(array $args = [])
 * @method \MageBackup\Aws\Result removePermission(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise removePermissionAsync(array $args = [])
 * @method \MageBackup\Aws\Result setEndpointAttributes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise setEndpointAttributesAsync(array $args = [])
 * @method \MageBackup\Aws\Result setPlatformApplicationAttributes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise setPlatformApplicationAttributesAsync(array $args = [])
 * @method \MageBackup\Aws\Result setSubscriptionAttributes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise setSubscriptionAttributesAsync(array $args = [])
 * @method \MageBackup\Aws\Result setTopicAttributes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise setTopicAttributesAsync(array $args = [])
 * @method \MageBackup\Aws\Result subscribe(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise subscribeAsync(array $args = [])
 * @method \MageBackup\Aws\Result unsubscribe(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise unsubscribeAsync(array $args = [])
 */
class SnsClient extends AwsClient {}
