<?php
namespace MageBackup\Aws\CloudWatchLogs;

use MageBackup\Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon CloudWatch Logs** service.
 *
 * @method \MageBackup\Aws\Result cancelExportTask(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise cancelExportTaskAsync(array $args = [])
 * @method \MageBackup\Aws\Result createExportTask(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createExportTaskAsync(array $args = [])
 * @method \MageBackup\Aws\Result createLogGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createLogGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result createLogStream(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createLogStreamAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteDestination(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteDestinationAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteLogGroup(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteLogGroupAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteLogStream(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteLogStreamAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteMetricFilter(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteMetricFilterAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteRetentionPolicy(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteRetentionPolicyAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteSubscriptionFilter(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteSubscriptionFilterAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeDestinations(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeDestinationsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeExportTasks(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeExportTasksAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeLogGroups(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeLogGroupsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeLogStreams(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeLogStreamsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeMetricFilters(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeMetricFiltersAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeSubscriptionFilters(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeSubscriptionFiltersAsync(array $args = [])
 * @method \MageBackup\Aws\Result filterLogEvents(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise filterLogEventsAsync(array $args = [])
 * @method \MageBackup\Aws\Result getLogEvents(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise getLogEventsAsync(array $args = [])
 * @method \MageBackup\Aws\Result putDestination(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise putDestinationAsync(array $args = [])
 * @method \MageBackup\Aws\Result putDestinationPolicy(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise putDestinationPolicyAsync(array $args = [])
 * @method \MageBackup\Aws\Result putLogEvents(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise putLogEventsAsync(array $args = [])
 * @method \MageBackup\Aws\Result putMetricFilter(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise putMetricFilterAsync(array $args = [])
 * @method \MageBackup\Aws\Result putRetentionPolicy(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise putRetentionPolicyAsync(array $args = [])
 * @method \MageBackup\Aws\Result putSubscriptionFilter(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise putSubscriptionFilterAsync(array $args = [])
 * @method \MageBackup\Aws\Result testMetricFilter(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise testMetricFilterAsync(array $args = [])
 */
class CloudWatchLogsClient extends AwsClient {}
