<script type="text/javascript">
//<![CDATA[
var socoIsMobile = true;
var homeIconUrl = '<?php echo $this->getSkinUrl('images/socolissimo/bg.png');?>';
//]]>
</script>
<?php

?>
<div id="layer_socolissimo" class="soco_layer"><div id="layer_socolissimo_wrapper" ></div>
<li id="socolissimo_description_domicile" class="descr" style="display:none;">
	<strong>Livraison &agrave; l'adresse de votre choix</strong> avec <strong>remise en bo&icirc;te aux lettres</strong> ou remise en mains propres selon les situations.<br/>
	En cas d'impossibilit&eacute;, votre colis sera mis &agrave; votre disposition en bureau de poste.
</li>
<li id="socolissimo_description_poste_fr" class="descr border" style="display:none;">
	Faites vous livrer dans l’un des <strong>bureaux de poste, relais pickup ou en consignes Pickup Station</strong> parmi 18 000 points de retrait au choix partout en France
</li>
<li id="socolissimo_description_poste_be" class="descr border" style="display:none;">
	Livraison dans l'un des commerces de proximité ou l'un des bureaux de Poste du réseau BPOST en Belgique.
</li>
<script type="text/javascript">
//<![CDATA[       
var socolissimoBaseUrl = '<?php echo $this->getUrl('socolissimo/ajax/') ?>';
if (aoGoToShippingMethodHooks == undefined) {
	var aoGoToShippingMethodHooks = new Array();
}
// initSocolissimoLogos : fonction définie dans socolissimo.js, appellée dans le hokk ci-dessous, pour charger les logos SoColissimo 
aoGoToShippingMethodHooks[aoGoToShippingMethodHooks.length] = initSocolissimoLogos;
if ((typeof Checkout) != "undefined") {
<?php if (version_compare(Mage::getVersion(), '1.8', '>=')) : ?>
	//On surchage la methode gotoSection de Checkout (voir opcheckout.js) : surcharge identique dans les modules addonline : socolissimo, GLS pour être compatible si on utilise les deux modules 
	Checkout.prototype.gotoSection = function (section, reloadProgressBlock) 
	{
		
	 		if (reloadProgressBlock) {
	            this.reloadProgressBlock(this.currentStep);
	        }
			//HOOK pour modules de livraison
	    	if (section == 'shipping_method') {
	    		
	    		for (i=0;i<aoGoToShippingMethodHooks.length;i++){
	    			
	    			aoGoToShippingMethodHooks[i]();
	    		} 
	    	}
	    	//Après le choix du mode de livraison il faut aussi recharger l'adresse de livraison car on a pu choisir un relais
			if (section == 'payment') {
	    		this.reloadProgressBlock('shipping');
	    	}
	    	this.currentStep = section;
	        var sectionElement = $('opc-' + section);
	        sectionElement.addClassName('allow');
	        this.accordion.openSection('opc-' + section);
	        if(!reloadProgressBlock) {
	            this.resetPreviousSteps();
	     }
    }
<?php else : ?>
	Checkout.prototype.gotoSection = function (section)
    {
		//HOOK pour modules de livraison
    	if (section == 'shipping_method') {
    		for (i=0;i<aoGoToShippingMethodHooks.length;i++){
    			aoGoToShippingMethodHooks[i]();
    		} 
    	}
    	//Après le choix du mode de livraison il faut aussi recharger l'adresse de livraison car on a pu choisir un relais
		if (section == 'payment') {
    		this.reloadProgressBlock('shipping');
    	}
    	var sectionElement = $('opc-'+section);
        sectionElement.addClassName('allow');
        this.accordion.openSection('opc-'+section);
        this.reloadProgressBlock(section);
    }
<?php endif; ?>    
}
//]]>
</script>
</div>