
<script type="text/javascript">
    Event.observe(document, "dom:loaded", function() {
        if (typeof window.twttr == 'undefined') {
            window.twttr = (function (d,s,id) {
                var t, js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return; js=d.createElement(s); js.id=id;
                js.src="//platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs);
                return window.twttr || (t = { _e: [], ready: function(f){ t._e.push(f) } });
            } (document, "script", "twitter-wjs"));
        }
    });
</script>