<?php $_collection = $this->getCollection() ?>

<div id="charttimeline" style="width: 100%; height: 400px;"></div>
<script type="text/javascript">
    var chart;
    var chartData = [];
    var date = null;
    <?php foreach (Mage::getModel('email/queue')->getCollection() as $_queue): ?>

        date = new Date(
            <?php echo date('Y', strtotime($_queue->getScheduledAt())) ?>,
            <?php echo date('m', strtotime($_queue->getScheduledAt())) ?>,
            <?php echo date('d', strtotime($_queue->getScheduledAt())) ?>,
            <?php echo date('H', strtotime($_queue->getScheduledAt())) ?>,
            <?php echo date('i', strtotime($_queue->getScheduledAt())) ?>,
            <?php echo date('s', strtotime($_queue->getScheduledAt())) ?>
        );
        chartData.push({
            date  : date,
            title : '<?php echo $_queue->getRecipientEmail() ?>',
            value : <?php echo $_queue->getTriggerId() ?>
        });
    <?php endforeach ?>

    AmCharts.ready(function () {
        chart                     = new AmCharts.AmSerialChart();
        chart.dataProvider        = chartData;
        chart.categoryField       = "date";
        chart.startDuration       = 0;
        // chart.depth3D             = 10;
        // chart.angle               = 30;
        chart.plotAreaBorderColor = "#DADADA";
        chart.plotAreaBorderAlpha = 1;
        // chart.rotate              = true;

        var categoryAxis = chart.categoryAxis;
        categoryAxis.gridAlpha = 0.07;
        categoryAxis.axisColor = "#DADADA";
        categoryAxis.startOnAxis = true;
        categoryAxis.parseDates = true

        var valueAxis = new AmCharts.ValueAxis();
        // valueAxis.stackType = "regular";
        valueAxis.gridAlpha = 0.07;
        valueAxis.title = "Total Emails";
        chart.addValueAxis(valueAxis);

        var graph = new AmCharts.AmGraph();
        graph.valueField  = "value";
        graph.title       = "Others (Cancled, Missed, Error)";
        graph.balloonText = "Others: [[title]]";
        graph.type        = "smoothedLine";
        graph.lineThickness = 2;
        graph.lineAlpha   = 1;
        graph.fillAlphas  = 0;
        graph.bulletSize = 5;
        chart.addGraph(graph);


        var legend = new AmCharts.AmLegend();
        chart.addLegend(legend);

        var chartCursor = new AmCharts.ChartCursor();
        chartCursor.zoomable = false; // as the chart displayes not too many values, we disabled zooming
        chartCursor.cursorAlpha = 0;
        chart.addChartCursor(chartCursor);

        chart.write("charttimeline");
    });
</script>



<div id="chartdiv" style="width: 100%; height: 400px;"></div>
<script type="text/javascript">
    var chart;
    var chartData = [];
    <?php foreach ($this->getCollection() as $_item): ?>
        chartData.push({
            title        : '<?php echo $_item->getPeriod() ?>',
            pending      : <?php echo intval($_item->getData('num_pending')) ?>,
            delivered    : <?php echo intval($_item->getData('num_delivered')) ?>,
            unsubscribed : <?php echo intval($_item->getData('num_unsubscribed')) ?>,
            others       : <?php echo intval($_item->getData('num_missed')) + intval($_item->getData('num_error')) + intval($_item->getData('num_canceled')) ?>
        });
    <?php endforeach ?>

    AmCharts.ready(function () {
        chart                     = new AmCharts.AmSerialChart();
        chart.dataProvider        = chartData;
        chart.categoryField       = "title";
        chart.startDuration       = 0;
        // chart.depth3D             = 10;
        // chart.angle               = 30;
        chart.plotAreaBorderColor = "#DADADA";
        chart.plotAreaBorderAlpha = 1;
        // chart.rotate              = true;

        var categoryAxis = chart.categoryAxis;
        categoryAxis.gridAlpha = 0.07;
        categoryAxis.axisColor = "#DADADA";
        categoryAxis.startOnAxis = true;

        var valueAxis = new AmCharts.ValueAxis();
        // valueAxis.stackType = "regular";
        valueAxis.gridAlpha = 0.07;
        valueAxis.title = "Total Emails";
        chart.addValueAxis(valueAxis);

        var graph = new AmCharts.AmGraph();
        graph.valueField  = "others";
        graph.title       = "Others (Cancled, Missed, Error)";
        graph.balloonText = "Others: [[value]]";
        graph.type        = "smoothedLine";
        graph.lineThickness = 2;
        graph.lineAlpha   = 1;
        graph.fillAlphas  = 0;
        graph.bulletSize = 5;
        chart.addGraph(graph);

        var graph = new AmCharts.AmGraph();
        graph.valueField  = "pending";
        graph.title       = "Pending Emails";
        graph.balloonText = "Pending: [[value]]";
        graph.type        = "smoothedLine";
        graph.lineAlpha   = 1;
        graph.lineThickness = 2;
        graph.fillAlphas  = 0;
        graph.bulletSize = 5;
        chart.addGraph(graph);

        var graph = new AmCharts.AmGraph();
        graph.valueField  = "delivered";
        graph.title       = "Delivered Emails";
        graph.balloonText = "Delivered: [[value]]";
        graph.type        = "smoothedLine";
        graph.lineAlpha   = 1;
        graph.lineThickness = 2;
        graph.fillAlphas  = 0.1;
        graph.bulletSize = 50;
        chart.addGraph(graph);

        var graph = new AmCharts.AmGraph();
        graph.valueField  = "unsubscribed";
        graph.title       = "Unsubscribed";
        graph.balloonText = "Unsubscribed: [[value]]";
        graph.type        = "smoothedLine";
        graph.lineAlpha   = 1;
        graph.lineThickness = 2;
        graph.fillAlphas  = 0;
        graph.bulletSize = 5;
        chart.addGraph(graph);

        

        var legend = new AmCharts.AmLegend();
        chart.addLegend(legend);

        var chartCursor = new AmCharts.ChartCursor();
        chartCursor.zoomable = false; // as the chart displayes not too many values, we disabled zooming
        chartCursor.cursorAlpha = 0;
        chart.addChartCursor(chartCursor);

        chart.write("chartdiv");
    });
</script>