<?php
namespace MageBackup\Aws\GameLift;

use MageBackup\Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon GameLift** service.
 *
 * @method \MageBackup\Aws\Result createAlias(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createAliasAsync(array $args = [])
 * @method \MageBackup\Aws\Result createBuild(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createBuildAsync(array $args = [])
 * @method \MageBackup\Aws\Result createFleet(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createFleetAsync(array $args = [])
 * @method \MageBackup\Aws\Result createGameSession(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createGameSessionAsync(array $args = [])
 * @method \MageBackup\Aws\Result createPlayerSession(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createPlayerSessionAsync(array $args = [])
 * @method \MageBackup\Aws\Result createPlayerSessions(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createPlayerSessionsAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteAlias(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteAliasAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteBuild(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteBuildAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteFleet(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteFleetAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteScalingPolicy(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteScalingPolicyAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeAlias(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeAliasAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeBuild(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeBuildAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeEC2InstanceLimits(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeEC2InstanceLimitsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeFleetAttributes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeFleetAttributesAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeFleetCapacity(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeFleetCapacityAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeFleetEvents(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeFleetEventsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeFleetPortSettings(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeFleetPortSettingsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeFleetUtilization(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeFleetUtilizationAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeGameSessionDetails(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeGameSessionDetailsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeGameSessions(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeGameSessionsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describePlayerSessions(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describePlayerSessionsAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeScalingPolicies(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeScalingPoliciesAsync(array $args = [])
 * @method \MageBackup\Aws\Result getGameSessionLogUrl(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise getGameSessionLogUrlAsync(array $args = [])
 * @method \MageBackup\Aws\Result listAliases(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listAliasesAsync(array $args = [])
 * @method \MageBackup\Aws\Result listBuilds(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listBuildsAsync(array $args = [])
 * @method \MageBackup\Aws\Result listFleets(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listFleetsAsync(array $args = [])
 * @method \MageBackup\Aws\Result putScalingPolicy(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise putScalingPolicyAsync(array $args = [])
 * @method \MageBackup\Aws\Result requestUploadCredentials(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise requestUploadCredentialsAsync(array $args = [])
 * @method \MageBackup\Aws\Result resolveAlias(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise resolveAliasAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateAlias(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateAliasAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateBuild(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateBuildAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateFleetAttributes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateFleetAttributesAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateFleetCapacity(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateFleetCapacityAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateFleetPortSettings(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateFleetPortSettingsAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateGameSession(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateGameSessionAsync(array $args = [])
 */
class GameLiftClient extends AwsClient {}
