<?php
namespace MageBackup\Aws\Kms;

use MageBackup\Aws\AwsClient;

/**
 * This client is used to interact with the **AWS Key Management Service**.
 *
 * @method \MageBackup\Aws\Result cancelKeyDeletion(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise cancelKeyDeletionAsync(array $args = [])
 * @method \MageBackup\Aws\Result createAlias(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createAliasAsync(array $args = [])
 * @method \MageBackup\Aws\Result createGrant(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createGrantAsync(array $args = [])
 * @method \MageBackup\Aws\Result createKey(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createKeyAsync(array $args = [])
 * @method \MageBackup\Aws\Result decrypt(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise decryptAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteAlias(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteAliasAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeKey(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeKeyAsync(array $args = [])
 * @method \MageBackup\Aws\Result disableKey(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise disableKeyAsync(array $args = [])
 * @method \MageBackup\Aws\Result disableKeyRotation(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise disableKeyRotationAsync(array $args = [])
 * @method \MageBackup\Aws\Result enableKey(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise enableKeyAsync(array $args = [])
 * @method \MageBackup\Aws\Result enableKeyRotation(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise enableKeyRotationAsync(array $args = [])
 * @method \MageBackup\Aws\Result encrypt(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise encryptAsync(array $args = [])
 * @method \MageBackup\Aws\Result generateDataKey(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise generateDataKeyAsync(array $args = [])
 * @method \MageBackup\Aws\Result generateDataKeyWithoutPlaintext(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise generateDataKeyWithoutPlaintextAsync(array $args = [])
 * @method \MageBackup\Aws\Result generateRandom(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise generateRandomAsync(array $args = [])
 * @method \MageBackup\Aws\Result getKeyPolicy(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise getKeyPolicyAsync(array $args = [])
 * @method \MageBackup\Aws\Result getKeyRotationStatus(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise getKeyRotationStatusAsync(array $args = [])
 * @method \MageBackup\Aws\Result listAliases(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listAliasesAsync(array $args = [])
 * @method \MageBackup\Aws\Result listGrants(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listGrantsAsync(array $args = [])
 * @method \MageBackup\Aws\Result listKeyPolicies(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listKeyPoliciesAsync(array $args = [])
 * @method \MageBackup\Aws\Result listKeys(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listKeysAsync(array $args = [])
 * @method \MageBackup\Aws\Result listRetirableGrants(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listRetirableGrantsAsync(array $args = [])
 * @method \MageBackup\Aws\Result putKeyPolicy(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise putKeyPolicyAsync(array $args = [])
 * @method \MageBackup\Aws\Result reEncrypt(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise reEncryptAsync(array $args = [])
 * @method \MageBackup\Aws\Result retireGrant(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise retireGrantAsync(array $args = [])
 * @method \MageBackup\Aws\Result revokeGrant(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise revokeGrantAsync(array $args = [])
 * @method \MageBackup\Aws\Result scheduleKeyDeletion(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise scheduleKeyDeletionAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateAlias(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateAliasAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateKeyDescription(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateKeyDescriptionAsync(array $args = [])
 */
class KmsClient extends AwsClient {}
