<?php
/**
 * Magmodules.eu - http://www.magmodules.eu - info@magmodules.eu
 * =============================================================
 * NOTICE OF LICENSE [Single domain license]
 * This source file is subject to the EULA that is
 * available through the world-wide-web at:
 * http://www.magmodules.eu/license-agreement/
 * =============================================================
 * @category    Magmodules
 * @package     Magmodules_Snippets
 * @author      Magmodules <info@magmodules.eu>
 * @copyright   Copyright (c) 2014 (http://www.magmodules.eu)
 * @license     http://www.magmodules.eu/license-agreement/
 * =============================================================
 */

if($alternate = $this->getAlternateData())
{
    if(isset($alternate['urls']))
    {
	    $alternate_urls = $alternate['urls'];
		if(count(array_unique($alternate_urls)) > 1)
        {
		    foreach($alternate_urls as $language => $url)
            {
				echo '<link rel="alternate" hreflang="' . $language . '" href="' . $url . '" />' . "\n";
			}
		}
	}

	if($this->getAlternateDebug())
    {
    	// ECHO STORE SETUP
	    if(isset($alternate['stores']))
        {
			$stores = $alternate['stores'];
			$store_html = '';
			foreach($stores as $store)
            {
				$group = $store['group'];
				$name = Mage::getModel('core/store')->load($store['store_id'])->getName();
				$store_html .= Mage::helper('alternatelang')->__('Storeview: %s (ID: %s) - Selected language code: %s', $name, $store['store_id'], $store['language_code']) . '<br/>';
			}
		}

		// CHECK FOR GROUP
		if(!isset($group))
        {
			$group = Mage::helper('alternatelang')->__('Not set');
		}

		$setup_html = Mage::helper('alternatelang')->__('Alternate Language: Group %s - Current store ID: %s', $group, Mage::app()->getStore()->getStoreId()) . '<br/>';
		echo '<p class="demo-notice" style="background-color: #E03F2C; color: #fff; text-align: center;"">' . $setup_html . '</p>';

		if($store_html)
        {
			echo '<p class="demo-notice" style="background-color: #B32927; color: #fff; text-align: center;">' . $store_html . '</p>';
		}

		// ECHO ALTERNATE LINKS
		if(isset($alternate['urls']))
        {
			$alternate_urls = $alternate['urls'];
			$link_html = '';
			foreach($alternate_urls as $language => $url)
            {
				$link_html .= htmlentities('<link rel="alternate" hreflang="' . $language . '" href="' . $url . '" />') . '<br/>';
			}
			if($link_html)
            {
				echo '<p class="demo-notice" style="background-color: #E03F2C; color: #fff; text-align: center;"">' . $link_html . '</p>';
			}
		}
		
		// ECHO ENCOUNTERED PROBLEMS
		if(isset($alternate['errors']))
        {
			echo '<p class="demo-notice" style="background-color: #B32927; color: #fff; text-align: center;">' . $alternate['errors'] . '</p>';		
		}
        else
        {
			if(count(array_unique($alternate_urls)) == 1)
            {
				echo '<p class="demo-notice" style="background-color: #B32927; color: #fff; text-align: center;">' . Mage::helper('alternatelang')->__('Only one URL found. URL cannot be a Alternate of is own.') . '</p>';				
			}
		}
	
	}
	
}