<script type="text/javascript">
    //<![CDATA[
    document.write('<a href="https://twitter.com/share" class="twitter-share-button rewardssocial-rewardable" data-text="<?php echo $this->getTweet(); ?>" <?php echo ($this->getTweetedUrl()) ? "data-url=" . $this->getTweetedUrl() : "" ?> <?php echo (!$this->isCounterEnabled()) ? "data-count=\"none\"" : "" ?>><?php echo $this->__("Tweet") ?></a>');
    //]]>
</script>