<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php
    $loggedin_cus_id=Mage::helper('customer')->getCustomer()->getEntityId() ;

    $wishList = Mage::getSingleton('wishlist/wishlist')->loadByCustomer($loggedin_cus_id);
    $wishListItemCollection = $wishList->getItemCollection();
    if(count($wishListItemCollection))
      {
      $arrProductIds = array();
        foreach ($wishListItemCollection as $item)
        {
         $product = $item->getProduct();
         $arrProductIds[] = $product->getId();
        }
      }

     $wishlistcoll =   Mage::helper('wishlist')->getWishlistItemCollection();
     $wishlistcollarray =   Mage::helper('wishlist')->getWishlistItemCollection()->getData();
     foreach($wishlistcoll as $item)
      {
        $itemarray[] = $item->getProductId();
      }
     $count = 0;
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php if($_product->isSaleable()): ?>

                	<?php if(Mage::getStoreConfig('ajax/addtocart/enabledpro')){ ?>

							<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
							<p class="pro-btn"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
							<span id='ajax_loader<?php echo $_product->getId()?>' style='display:none;float:left'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>
							<?php } else { ?>
								<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
								<a href='<?php echo $this->getUrl('ajax/ajax/productoptions',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Test</a>
							<?php }  ?>

						<?php }else{ ?>
						 <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>

					<?php } ?>
					
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <?php if(Mage::getStoreConfig('ajax/wishlistcompare/enabledpro')){?>
					 <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <?php if(in_array($_product->getId(), $arrProductIds))
                                 { $checkUser=1; }
                              else{ $checkUser=0; }
                             $wishlist = Mage::getModel('wishlist/item')->load($_product->getId(),'product_id');
                             if($wishlist->getId() && $checkUser==1)
                             {
                              if(in_array($_product->getId(), $itemarray))
                                {
                                 $itemId = $wishlistcollarray[$count]['wishlist_item_id'];
                                 $itemLoad = Mage::getModel('wishlist/item')->load($itemId);
                              ?>
                            <li><a href="#" onclick='if(confirm("Are you sure you would like to remove this item from the wishlist?")) { removeWishlist("<?php echo $this->helper('wishlist')->getRemoveUrl($itemLoad) ?>","<?php echo $_product->getId()?>");return false;}' class="link-wishlist"><span class="fabShopSprite" id="wishlist<?php echo $_product->getId()?>"><?php echo $this->__('Remove from Wishlist') ?></span></a></li>
                            <?php $count++; } ?>
                            <?php } else { ?>
                            <li><a href="#" onclick='ajaxWishlist("<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>","<?php echo $_product->getId()?>");return false;' class="link-wishlist"><span class="fabShopSprite" id="wishlist<?php echo $_product->getId()?>"><?php echo $this->__('Add to Wishlist') ?></span></a></li>
                            <?php } ?>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="#" onclick='ajaxCompare("<?php echo $this->getAddToCompareUrl($_product); ?>","<?php echo $_product->getId()?>");return false;' class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                    <span id='ajax_loading<?php echo $_product->getId()?>' style='display:none;float:left'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>

                    <?php }else{?>
					<ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
						  </ul>
					<?php } ?>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                    	<?php if(Mage::getStoreConfig('ajax/addtocart/enabledpro')){ ?>

							<?php if ( !($_product->getTypeInstance(true)->hasOptions($_product) || $_product->isGrouped()) ) { ?>
							<p class="pro-btn"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
							<span id='ajax_loader<?php echo $_product->getId()?>' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>
							<?php } else { ?>
								<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
								<a href='<?php echo $this->getUrl('ajax/ajax/productoptions',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Link</a>
							<?php }  ?>
						
						<?php }else{ ?>
						 <p class="pro-btn"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
						
					<?php } ?>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>


                	<?php if(Mage::getStoreConfig('ajax/wishlistcompare/enabledpro')){?>
					 <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <?php if(in_array($_product->getId(), $arrProductIds))
                                 { $checkUser=1; }
                              else{ $checkUser=0; }
                             $wishlist = Mage::getModel('wishlist/item')->load($_product->getId(),'product_id');
                             if($wishlist->getId() && $checkUser==1)
                             {
                              if(in_array($_product->getId(), $itemarray))
                                {
                                 $itemId = $wishlistcollarray[$count]['wishlist_item_id'];
                                 $itemLoad = Mage::getModel('wishlist/item')->load($itemId);
                              ?>

                            <li><a href="#" onclick='if(confirm("Are you sure you would like to remove this item from the wishlist?")) {removeWishlist("<?php echo $this->helper('wishlist')->getRemoveUrl($itemLoad) ?>","<?php echo $_product->getId()?>");return false;}' class="link-wishlist"><span class="fabShopSprite" id="wishlist<?php echo $_product->getId()?>"><?php echo $this->__('Remove from Wishlist') ?></span></a></li>
                            <?php $count++; } ?>
                            <?php } else { ?>
                            <li><a href="#" onclick='ajaxWishlist("<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>","<?php echo $_product->getId()?>");return false;' class="link-wishlist"><span class="fabShopSprite" id="wishlist<?php echo $_product->getId()?>"><?php echo $this->__('Add to Wishlist') ?></span></a></li>
                            <?php } ?>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="#" onclick='ajaxCompare("<?php echo $_compareUrl ?>","<?php echo $_product->getId()?>");return false;' class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                    <span id='ajax_loading<?php echo $_product->getId()?>' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>

					<?php }else{?>
					<ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
						  </ul>
					<?php } ?>

                  
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
<div class="addtocart_popup" id="addtocart_popup" style="position:absolute;display:none;">
	<div class="popup-text"></div>
	<div class="popup-buttons" >
		<div class="contine_shopping_btn">
			<button onclick="jQuery.fancybox.close();" class="button btn-shop" title="<?php echo $this->__('Continue Shopping'); ?>" type="button"><span><span><?php echo $this->__('Continue Shopping'); ?></span></span></button>
		</div>
		<div class="proceed_checkout_btn">
			<button onclick="setLocation('<?php echo $this->getUrl('checkout/cart');?>');" class="button btn-shop" title="<?php echo $this->__('Proceed to Checkout'); ?>" type="button"><span><span><?php echo $this->__('View cart & checkout'); ?></span></span></button>
		</div>
	</div>
</div>
<script type="text/javascript">
	jQuery.noConflict();
	jQuery(document).ready(function(){
		jQuery('.fancybox').fancybox(
			{
			   hideOnContentClick : true,
			   width: 520,
			   autoDimensions: true,
               type : 'iframe',
			   showTitle: false,
			   scrolling: 'no',
			   onComplete: function(){
				jQuery('#fancybox-frame').load(function() { // wait for frame to load and then gets it's height
					jQuery('#fancybox-content').height(jQuery(this).contents().find('body').height()+30);
					jQuery.fancybox.resize();
				 });

			   }
			}
		);
	});
	function showOptions(id){
		jQuery('#fancybox'+id).trigger('click');
	}
	function setAjaxData(data,iframe){
		if(data.status == 'ERROR'){
			//alert(data.message);
            jQuery('.popup-text').html(data.message);
                    jQuery.fancybox({
    		                 'content' : jQuery("#addtocart_popup").html(),
    						 'padding' : 20,
    				         });

		}else{
			if(jQuery('.block-cart')){
	            jQuery('.block-cart').replaceWith(data.sidebar);
	        }
	        if(jQuery('.header .links')){
	            jQuery('.header .links').replaceWith(data.toplink);
	        }

            url_topcart = "<?php echo $this->getUrl('ajax/ajax/headercart');?>";
                        jQuery.ajax({
              	                url: url_topcart,
              					type:"POST",
              					data:{},
              					success: function(data)
                                    {
                                       jQuery('.top-link-cart:first').parent("li").html(data);

                                       jQuery('.fancybox').fancybox({
                                      			    hideOnContentClick : true,
                                      			    width: 520,
                                      			    autoDimensions: true,
                                                    type : 'iframe',
                                      			    showTitle: false,
                                      			    scrolling: 'no',
                                      			    onComplete: function(){
                                      				jQuery('#fancybox-frame').load(function() {
                                      				jQuery('#fancybox-content').height(jQuery(this).contents().find('body').height()+30);
                                      				jQuery.fancybox.resize();
                                      				 });
                                      			   }
                                      			});
                                       truncted_details();
                                       displayTopCart();
              					      }
              				    });

	        //jQuery.fancybox.close();

            jQuery('.popup-text').html(data.message);
                    jQuery.fancybox({
    		                 'content' : jQuery("#addtocart_popup").html(),
    						 'padding' : 20,
                             'minWidth': 300,
    				         });

		}

	}

	function setLocationAjax(url,id){
		url += 'isAjax/1';
		url = url.replace("checkout/cart","ajax/cart");
        showproductloading();            
		try {
			jQuery.ajax( {
				url : url,
				dataType : 'json',
				success : function(data)
                   { jQuery("#pro-loading").remove();
                     jQuery("#pro-img").remove();
         			 setAjaxData(data,false);
			     	}

			});
		} catch (e) {
		}
	}

   var url_headercart = "<?php echo $this->getUrl('ajax/ajax/headercart') ?>";

</script>