<?php
namespace MageBackup\Aws\CognitoIdentityProvider;

use MageBackup\Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon Cognito Identity Provider** service.
 * 
 * @method \MageBackup\Aws\Result addCustomAttributes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise addCustomAttributesAsync(array $args = [])
 * @method \MageBackup\Aws\Result adminConfirmSignUp(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise adminConfirmSignUpAsync(array $args = [])
 * @method \MageBackup\Aws\Result adminDeleteUser(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise adminDeleteUserAsync(array $args = [])
 * @method \MageBackup\Aws\Result adminDeleteUserAttributes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise adminDeleteUserAttributesAsync(array $args = [])
 * @method \MageBackup\Aws\Result adminDisableUser(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise adminDisableUserAsync(array $args = [])
 * @method \MageBackup\Aws\Result adminEnableUser(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise adminEnableUserAsync(array $args = [])
 * @method \MageBackup\Aws\Result adminGetUser(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise adminGetUserAsync(array $args = [])
 * @method \MageBackup\Aws\Result adminResetUserPassword(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise adminResetUserPasswordAsync(array $args = [])
 * @method \MageBackup\Aws\Result adminSetUserSettings(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise adminSetUserSettingsAsync(array $args = [])
 * @method \MageBackup\Aws\Result adminUpdateUserAttributes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise adminUpdateUserAttributesAsync(array $args = [])
 * @method \MageBackup\Aws\Result changePassword(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise changePasswordAsync(array $args = [])
 * @method \MageBackup\Aws\Result confirmForgotPassword(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise confirmForgotPasswordAsync(array $args = [])
 * @method \MageBackup\Aws\Result confirmSignUp(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise confirmSignUpAsync(array $args = [])
 * @method \MageBackup\Aws\Result createUserPool(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createUserPoolAsync(array $args = [])
 * @method \MageBackup\Aws\Result createUserPoolClient(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise createUserPoolClientAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteUser(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteUserAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteUserAttributes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteUserAttributesAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteUserPool(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteUserPoolAsync(array $args = [])
 * @method \MageBackup\Aws\Result deleteUserPoolClient(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise deleteUserPoolClientAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeUserPool(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeUserPoolAsync(array $args = [])
 * @method \MageBackup\Aws\Result describeUserPoolClient(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise describeUserPoolClientAsync(array $args = [])
 * @method \MageBackup\Aws\Result forgotPassword(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise forgotPasswordAsync(array $args = [])
 * @method \MageBackup\Aws\Result getUser(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise getUserAsync(array $args = [])
 * @method \MageBackup\Aws\Result getUserAttributeVerificationCode(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise getUserAttributeVerificationCodeAsync(array $args = [])
 * @method \MageBackup\Aws\Result listUserPoolClients(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listUserPoolClientsAsync(array $args = [])
 * @method \MageBackup\Aws\Result listUserPools(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listUserPoolsAsync(array $args = [])
 * @method \MageBackup\Aws\Result listUsers(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise listUsersAsync(array $args = [])
 * @method \MageBackup\Aws\Result resendConfirmationCode(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise resendConfirmationCodeAsync(array $args = [])
 * @method \MageBackup\Aws\Result setUserSettings(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise setUserSettingsAsync(array $args = [])
 * @method \MageBackup\Aws\Result signUp(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise signUpAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateUserAttributes(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateUserAttributesAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateUserPool(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateUserPoolAsync(array $args = [])
 * @method \MageBackup\Aws\Result updateUserPoolClient(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise updateUserPoolClientAsync(array $args = [])
 * @method \MageBackup\Aws\Result verifyUserAttribute(array $args = [])
 * @method \MageBackup\GuzzleHttp\Promise\Promise verifyUserAttributeAsync(array $args = [])
 */
class CognitoIdentityProviderClient extends AwsClient {}
