<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div class="product-view">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="product-shop">
            <div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
            </div>

            <?php if ($this->canEmailToFriend()): ?>
                <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
            <?php endif; ?>

            <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
            <?php echo $this->getChildHtml('alert_urls') ?>
            <?php echo $this->getChildHtml('product_type_data') ?>
            <?php echo $this->getTierPriceHtml() ?>
            <?php echo $this->getChildHtml('extrahint') ?>

            <?php if (!$this->hasOptions()):?>
                <div class="add-to-box">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                            <span class="or"><?php echo $this->__('OR') ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
                <?php echo $this->getChildHtml('extra_buttons') ?>
            <?php endif; ?>

            <?php if ($_product->getShortDescription()):?>
                <div class="short-description">
                    <h2><?php echo $this->__('Quick Overview') ?></h2>
                    <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                </div>
            <?php endif;?>

            <?php echo $this->getChildHtml('other');?>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>

        </div>

        <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>

        <div class="clearer"></div>
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
    </form>
    <div class="addtocart_popup" id="addtocart_popup" style="position:absolute;display:none;">
	<div class="popup-text"></div>
	<div class="popup-buttons" >
		<div class="contine_shopping_btn">
			<button onclick="jQuery.fancybox.close();" class="button btn-shop" title="<?php echo $this->__('Continue Shopping'); ?>" type="button"><span><span><?php echo $this->__('Continue Shopping'); ?></span></span></button>
		</div>
		<div class="proceed_checkout_btn">
			<button onclick="setLocation('<?php echo $this->getUrl('checkout/cart');?>');" class="button btn-shop" title="<?php echo $this->__('Proceed to Checkout'); ?>" type="button"><span><span><?php echo $this->__('View cart & checkout'); ?></span></span></button>
		</div>
	</div>
    </div>
     <script type="text/javascript">
        var cart_url= "<?php echo $this->getUrl('checkout/cart'); ?>";
        var estimateRegionId = "<?php echo $this->getEstimateRegionId() ?>";
        var region_json = <?php echo $this->helper('directory')->getRegionJson() ?>;
    </script>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
    	productAddToCartForm.submit = function(button, url) {
		if (this.validator.validate()) {
			var form = this.form;
			var oldUrl = form.action;
			if (url) {
				form.action = url;
			}
			var e = null;
			// Start of our new ajax code
			if (!url) {
				url = jQuery('#product_addtocart_form').attr('action');
			}
			url = url.replace("checkout/cart","ajax/cart"); // New Code
			var data = jQuery('#product_addtocart_form').serialize();
			data += '&isAjax=1';
            showviewloading();
			try {
				jQuery.ajax( {
					url : url,
					dataType : 'json',
					type : 'post',
					data : data,
					success : function(data) {
					    jQuery("#pro-view-loading").remove();
                        jQuery("#pro-view-img").remove();
						if(data.status == 'ERROR'){
							alert(data.message);
						}else{
    	                        if(jQuery('.block-cart')){
    	                            jQuery('.block-cart').replaceWith(data.sidebar);
    	                        }
    	                        if(jQuery('.header .links')){
    	                            jQuery('.header .links').replaceWith(data.toplink);
    	                        }

                           var itemid = data.item_id;
                           var new_url = jQuery('#product_addtocart_form').attr('action');
                           var new_url_length = new_url.indexOf("id/")+3;
                           var last_string = new_url.substr(0,new_url_length)+''+itemid+'/';
                           jQuery("#product_addtocart_form").attr('action',last_string);

                                url_topcart = "<?php echo $this->getUrl('ajax/ajax/headercart') ?>";
                                jQuery.ajax({
                        	                url: url_topcart,
                        					type:"POST",
                        					data:{},
                        					success: function(data)
                                              {
                            				      var returndata = data;
                                                  jQuery('.top-link-cart:first').parent("li").html(returndata);
                                                  truncted_details();
                                                  displayTopCart();
                          					   }
                        				    });
                                jQuery('.popup-text').html(data.message);
                                jQuery.fancybox({
    							            'content' : jQuery("#addtocart_popup").html(),
    										'padding' : 20,
                                            'minWidth': 300,
    				                    });

						    }

					}
				});
			} catch (e) {
			}
			// End of our new ajax code
			this.form.action = oldUrl;
			if (e) {
				throw e;
			}
		}
	}.bind(productAddToCartForm);
    productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>

     function truncted_details()
       {
          $$('.truncated').each(function(element){
              Event.observe(element, 'mouseover', function(){
              if (element.down('div.truncated_full_value')) {
              element.down('div.truncated_full_value').addClassName('show')
              }
              });
              Event.observe(element, 'mouseout', function(){
              if (element.down('div.truncated_full_value')) {
              element.down('div.truncated_full_value').removeClassName('show')
              }
              });
          });
       }
     
    </script>

    </div>

    <div class="product-collateral">
<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
        <div class="box-collateral <?php echo "box-{$alias}"?>">
            <?php if ($title = $this->getChildData($alias, 'title')):?>
            <h2><?php echo $this->escapeHtml($title); ?></h2>
            <?php endif;?>
            <?php echo $html; ?>
        </div>
<?php endforeach;?>
        <?php echo $this->getChildHtml('upsell_products') ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>
    </div>
</div>
