<?php

class TBT_Rewards_Helper_Metrics_Revenue_Members extends TBT_Rewards_Helper_Metrics_Revenue
{

    /**
     * Overwrites parent method and calculates total revenue generated by loyalty program members
     * in the applied period.
     *
     * @param  array  $array
     * @return TBT_Rewards_Helper_Metrics_Revenue_Members
     */
    protected function _prepareSeries($series = array())
    {
        if (is_null($series)) {
            return $this;
        }

        $membersRevenue = 0;
        foreach ($series as $key => $value) {
            if ($value['is_member']) {
                $membersRevenue += $value['total_revenue_amount'];
            }
        }

        $membersRevenue = $this->_formatContentAsCurrency($membersRevenue);

        $this->addSeries(array(
            'title'   => 'Members Total Revenue',
            'content' => $membersRevenue,
            // 'note' => ''
        ));

        return $this;
    }

}
