
<?php if (!$this->getAttributeCode()): ?>
    <?php foreach ($this->getAttributeList() as $code => $attribute): ?>
        <?php if (Mage::helper('aitmanufacturers')->getIsActive($code)): ?>
            <?php echo $this->getLayout()->createBlock('aitmanufacturers/manufacturers_brief', 'manufacturers.brief.'.$code )->setAttributeCode($code)->setTemplate('aitmanufacturers/manufacturers_brief.phtml')->toHtml(); ?>
        <?php endif ?>
    <?php endforeach; ?>
<?php else: ?>
    <?php $manufacturers = $this->getItems() ?>
    <?php $i=1; ?>
    <?php //$showBriefIcons = Mage::getStoreConfig('catalog/aitmanufacturers/manufacturers_show_brief_image', Mage::app()->getStore()->getId()); ?>
    <?php $showBriefIcons = Mage::helper('aitmanufacturers')->getConfigParam('show_brief_image', $this->getAttributeCode() ,Mage::app()->getStore()->getId()); ?>
    <?php if (count($manufacturers)): ?>

    <div class="block block-<?php echo $this->getAttributeCode(); ?>" <?php if($this->getAttributeCode()=='gamme_collection_new'): ?>style="display:none;"<?php endif; ?>>

        <div class="block-title">
            <strong style="background-image:none;"><span><?php echo Mage::helper('aitmanufacturers')->__(Mage::helper('aitmanufacturers')->getAttributeName($this->getAttributeCode())) ?></span></strong>
        </div>

        <div class="block-content">

            <ol>
            <?php foreach ($manufacturers as $manufacturer): ?>
                <li class="item <?php echo ($i%2)?'odd':'even'; ?>">
                    <p class="product-name">
                     <!--	<?php if($showBriefIcons && $manufacturer->getListImage() && $manufacturer->getShowBriefImage()){ ?><a href="<?php echo $manufacturer->getUrl() ?>" style="text-decoration:none;"><img src="<?php echo Mage::helper('aitmanufacturers/image')->getIconUrl($manufacturer->getListImage()) ?>" alt="<?php echo $this->htmlEscape($manufacturer->getManufacturer()) ?>" style="vertical-align:middle;" /></a> <?php } ?>  -->
                    	<a href="<?php echo $manufacturer->getUrl() ?>"><?php echo $this->htmlEscape($manufacturer->getManufacturer()) ?></a></p>
                </li>
                <?php $i++; ?>
            <?php endforeach ?>
            </ol>

            <?php if ($this->getTotal() > count($manufacturers)): ?>
                <div class="actions"><a href="<?php echo Mage::helper('aitmanufacturers')->getManufacturersUrl($this->getAttributeCode()) ?>" title="<?php echo $this->__('Full list of Attributes')?>"  style="float:none;"><?php echo $this->__('View All')?></a></div>
            <?php endif ?>

        </div>
    </div>
    <?php endif ?>
  <?php endif ?>