

<script type="text/javascript">

    CAPTION_POINT = '<?php echo $this->__('Point'); ?>';
    CAPTION_POINTS = '<?php echo $this->__('Points'); ?>';
    CAPTION_YOU_WILL_SPEND = '<?php echo $this->__('Customer Will Spend'); ?>';
    CAPTION_WITH = '<?php echo $this->__('with'); ?>';
    CAPTION_CANNOT_USE_POINTS = "<?php echo $this->__("You cannot use points until you login or create a new account.") ?>";
    CAPTION_NOT_ENOUGH_POINTS = "<?php echo $this->__("The customer doesn't have enough points to use this redemption rule.") ?>";
    CAPTION_REFRESHING_CART = '<?php echo $this->__("Refreshing cart, please wait..") ?>';

</script>