<script>
    var MPM_URL_UPDATE_PRODUCT = '<?php echo $this->getUrl('*/*/changeSetting', array('product_id' => '#product_id#', 'channel' => '#channel#', 'field' => '#field#', 'value' => '#value#')); ?>';
</script>

<?php if($this->getTitle()): ?>
    <h3><?php echo $this->getTitle() ?></h3>
<?php endif ?>
<?php if(!empty($tabs)): ?>
    <ul id="<?php echo $this->getId() ?>" class="tabs-horiz">
        <?php foreach ($tabs as $_tab): ?>
            <li>
                <a href="<?php echo $this->getTabUrl($_tab)?>" id="<?php echo $this->getTabId($_tab) ?>" title="<?php echo $this->getTabTitle($_tab) ?>" class="tab-item-link <?php echo $this->getTabClass($_tab) ?><?php if (preg_match('/\s?ajax\s?/', $this->getTabClass($_tab))) {?> notloaded<?php }?>">
                    <span><span class="changed" title="<?php echo $this->__('The information in this tab has been changed.') ?>"></span><span class="error" title="<?php echo $this->__('This tab contains invalid data. Please solve the problem before saving.') ?>"></span><?php echo $this->getTabLabel($_tab) ?></span>
                </a>
                <div id="<?php echo $this->getTabId($_tab) ?>_content" style="display:none"><?php echo $this->getTabContent($_tab) ?></div>
            </li>
        <?php endforeach; ?>
    </ul>
    <script type="text/javascript">

        <?php echo $this->getId() ?>JsTabs = new varienTabs('<?php echo $this->getId() ?>', '<?php echo $this->getDestElementId() ?>', '<?php echo $this->getActiveTabId() ?>', <?php echo $this->getAllShadowTabs()?>);
    </script>
<?php endif; ?>

<div id="loading-mask" style="display:none">
    <p class="loader" id="loading_mask_loader"><img src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif'); ?>" alt="Loading..."/><br/>Please wait...</p>
</div>