<script>
    M2ePro.translator.add(<?php echo json_encode(array(
        'Migration Information' => Mage::helper('M2ePro')->__('Migration Information'),
    )); ?>);

    Event.observe(window, 'load', function() {
        AdvancedHandlerObj = new ConfigurationAdvancedHandler();
    });
</script>

<div class="entry-edit" id="magento_block_configuration_advanced_data" collapseable="no">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Migration to Magento v2.x.x'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tbody>

                <tr>
                    <td class="label" style="width: auto">
                        <label style="width: auto"><?php echo Mage::helper('M2ePro')->__('Stop module and prepare for migration'); ?>: </label>
                    </td>

                    <td class="value">
                        <?php echo $this->getChildHtml('proceed_button'); ?>
                    </td>
                </tr>

                </tbody>

            </table>

        </div>
    </div>

</div>

<script type="M2ePro/template" id="information_content">

    <div class="entry-edit" id="magento_block_configuration_advanced_data" collapseable="no">

        <div style="margin-top: 10px">
            <p>
                <?php echo Mage::helper('M2ePro')->__('
                    <strong>Note:</strong> For successful data migration from M2E Pro for Magento v1.x to M2E Pro for Magento v2.x, please, take a time to review the <a target="_blank" href="http://docs.m2epro.com/x/mQQtAQ">Migration guidelines</a>.
                    Also, we recommend to proceed firstly on the staging environment to prevent any issues with the live data.

                    For the Module Migration to Magento v2.x, you should press a <strong>Confirm</strong> button which will start automatically several required steps for the data migration described below:
                    <br />
                    <ul style="margin-left: 15px;">
                        <li>1) M2E Pro dynamic tasks run by Cron such as automatic synchronization of orders and inventory, etc will be disabled.</li>
                        <li>2) the Interface will be blocked to prevent any changes made to the current data.</li>
                        <li>3) the data in the database will be accommodated to be used in Magento v2.x</li>
                    </ul>
                    <br />
                    <strong>Note:</strong> please, be thoughtful before starting the Migration process as it cannot be reverted back. The data will be prepared to be used in the new Module and there will be no way to automatically revert it to Magento v1.x Module.
                '); ?>
            </p>
        </div>

        <div style="float: right; margin: 0 0 1em;">
            <a href="#" onclick="adnvancedPopup.close();">Close</a>
            &nbsp;
            &nbsp;
            &nbsp;
            <?php echo $this->getChildHtml('confirm_button');?>
        </div>

    </div>

</script>