<div id="block_notice_common_configuration_general" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('General'); ?>">
    <?php echo Mage::helper('M2ePro')->__('
        This section allows you to configure the general settings for the interaction between M2E Pro Module and Amazon marketplaces.<br />
        You can enable Amazon Business (B2B) to use Business Price and QTY Discounts for your Offers.<br /><br />
        <strong>Note:</strong> Amazon Business is available for the <strong>US</strong>, <strong>UK</strong>, <strong>DE</strong> marketplaces only.
    '); ?>
</div>