
<script type="text/javascript">

    // Other PHP content ///////////////
    currency_map  = <?php echo $this->getCurrencyMapJson(); ?>;

    feignPriceChange = function() {
    
    };

</script>

<div class="slider" onmouseup="sliderNotSliding()">
    <table cellspacing="0" cellpadding="0">
        <tbody>
            <tr>
                <td style="vertical-align:middle" class="btn-slider-reduce-points-container">
                    <img class="btn-slider-reduce-points" alt="<?php echo $this->__('Spend one point less'); ?>" 
                         src="<?php echo $this->getSkinUrl('rewards/images/slider/decr_points.gif'); ?>" 
                         id="slider_reduce_points"
                         onclick="rSlider.decr()" 
                         style="position:relative; top:5px;" />
                </td>
                <td>
                    <div class="sliderRail" id="sliderRail">
                        <a style="left: 0%;" class="sliderHandle ui-slider-handle ui-state-default" id="sliderHandle"
                           onmousedown="sliderSliding()"  
                           onmouseup="sliderNotSliding()"></a>
                    </div>
                </td>
                <td style="vertical-align: middle" class="btn-slider-reduce-points-container">
                    <img class="btn-slider-increase-points" 
                         alt="<?php echo $this->__('Spend one point more'); ?>" 
                         src="<?php echo $this->getSkinUrl('rewards/images/slider/incr_points.gif'); ?>" 
                         id="slider_reduce_points"
                         onclick="rSlider.incr()" 
                         style="position:relative; top:5px;" />
                </td>
                <td valign="top" class="cartSlider_cell">
                </td>
            </tr>
        </tbody>
    </table>
    <div id="sliderCaption" class="cartSlider_caption">
    </div>
    <input type="hidden" name="redemption_uses" id="redemption_rule_uses"/>
</div>
<script type="text/javascript">
    (function() {
        var onload = function() {
            // Hack: use a timeout to make sure that this runs AFTER the js from minicart_js
            setTimeout(function() {
                var min_spendable = <?php echo (string) $this->getMinSpendablePoints(); ?>;
                var max_spendable = <?php echo (string) $this->getMaxSpendablePoints(); ?>;
                var step = <?php echo (string) $this->getPointsStep(); ?>;
                var current_value = <?php echo (string) $this->getCurrentSpendingPoints(); ?>;

                rSlider = new RedemptionSlider('sliderHandle', 'sliderRail', 'sliderCaption', 'redemption_rule_uses');
                rSlider.regenerateSlider(min_spendable, max_spendable, step, current_value);//min, max, step, initial_value
                rSlider.setExternalValue(current_value);
            }, 50);
        };

        if (document.loaded) {
            onload();
        } else {
            document.observe("dom:loaded", onload);
        }
    })();

    // Functions for changing the cursor on the slider
    sliderSliding = function() {
        $('sliderRail').addClassName('sliderRail-sliding'); 
        $('sliderHandle').addClassName('sliderHandle-sliding');
    };

    sliderNotSliding = function() {
        $('sliderRail').removeClassName('sliderRail-sliding'); 
        $('sliderHandle').removeClassName('sliderHandle-sliding');
    };
</script>
