<?php
/**
 * Video Plugin for Magento
 * 
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Niveus
 * @package    Niveus_ProductVideo
 * @copyright  Copyright (c) 2013 Niveus Solutions (http://www.niveussolutions.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Niveus Solutions <support@niveussolutions.com>
 */
?>

<?php 
  $_productVideos = $this->_getProductVideos();
  $a=0;

?>
<?php if($_productVideos && $_productVideos->count() > 0):?>
   <h3><?php echo $this->__('Product Videos') ?></h3>



   <?php foreach($_productVideos as $video) : ?>  
        <?php $videourl = $this->getCode($video);?>
        
        <?php if($this->is_youtube($videourl)):?>
        	 <!-- video from youtube -->
        	 <?php $video_code = $this->youtube_video_id($videourl);?>
             <?php echo "<iframe width=\"560\" height=\"315\" src=\"http://www.youtube.com/embed/$video_code?rel=0\" frameborder=\"0\"></iframe>";?>
        <?php elseif($this->is_vimeo($videourl)):?> 
             <?php $video_code = $this->vimeo_video_id($videourl);?> 
             <?php echo "<iframe src=\"http://player.vimeo.com/video/$video_code?title=0&byline=0&portrait=0;loop=0\" width=\"560\" height=\"315\" frameborder=\"0\"></iframe>"; ?>        
        <?php endif; ?>
                      
   <?php endforeach; ?>

<?php endif;?>
