<div id="block_notice_common_logs_listings_grid" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Listings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This Log contains all information about Actions, which were done on all M2E Pro Listings and their Items.');

    $components = Mage::helper('M2ePro/View_Common_Component')->getActiveComponents();
    if (count($components) == 1) : ?>
        <?php
        $component = array_shift($components);
            if ($component == Ess_M2ePro_Helper_Component_Amazon::NICK) {
                $url = Mage::helper("M2ePro/Module_Support")->getDocumentationUrl(NULL, NULL, "x/foIVAQ#Logs-ListingsLog");
            } else {
                $url = Mage::helper('M2ePro/Module_Support')->getDocumentationUrl($component, 'Logs#Logs-ListingsLog');
            }
        ?>
        <?php echo Mage::helper('M2ePro')->__('
            <br/><br/>More detailed information about ability to work with this Page you can find <a href="%url%" target="_blank">here</a>.',
            $url
        ); ?>
    <?php else : ?>
        <?php echo Mage::helper('M2ePro')->__('
            <br/><br/>More detailed information about ability to work with this page you can find on <a target="_blank" href="%url1%">%amazon%</a> and
            <a target="_blank" href="%url2%">%buy%</a>.',
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/foIVAQ#Logs-ListingsLog'),
            Mage::helper('M2ePro/Component_Amazon')->getTitle(),
            Mage::helper('M2ePro/Module_Support')->getDocumentationUrl(NULL, NULL, 'x/iIMVAQ#Logs-ListingsLog'),
            Mage::helper('M2ePro/Component_Buy')->getTitle()
        ); ?>
    <?php endif; ?>
</div>