<?php
/**
 * @var $_product   Mage_Catalog_Model_Product
 */
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $helpZoom = $this->helper('infortis_cloudzoom');
    $helpImg = $this->helper('infortis/image');

    //Get image sizes. If height is not specified, aspect ratio will be kept.
    $imgWidth       = intval($helpZoom->getCfg('images/main_width'));
    $imgHeight      = intval($helpZoom->getCfg('images/main_height'));
    $bigImageWidth  = intval($helpZoom->getCfg('general/big_image_width'));
    $bigImageHeight = intval($helpZoom->getCfg('general/big_image_height'));
    $thumbImgWidth  = 65; //intval($helpZoom->getCfg('images/thumbnail_width'));
    $thumbImgHeight = 65; //intval($helpZoom->getCfg('images/thumbnail_height'));

    //If main image width is not specified, use default values
    if ($imgWidth <= 0)
    {
        $imgWidth = 363;
        $imgHeight = 363;
    }
    //$imgBorder = 1;
    //$imgPadd = 5;
    //$imgTotalPadd = ($imgBorder + $imgPadd) * 2; //12
    //$imgWidth -= $imgTotalPadd;
    //$imgHeight -= $imgTotalPadd;

    //If main image width is not specified, use default values
    if ($bigImageWidth <= 0)
    {
        $bigImageWidth = 650;
        $bigImageHeight= 650;
    }

    //Aspect ratio settings
    if ($helpZoom->getCfg('images/aspect_ratio'))
    {
        //Height will be calculated automatically based on width to keep the aspect ratio of each image
        $imgHeight = 0;
        $bigImageHeight= 0;
        $thumbImgHeight = 0;
    }
?>



<?php //Main image ?>

<div class="img-box img-box-style1">
<?php $video = $this->getVideos()->getFirstItem(); ?>
<?php /* Main condition removed to keep normal display even if there's no main image in the product ?>
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<?php */ ?>

    <?php if($helpZoom->isCloudZoomEnabled()): //If module enabled ?>

        <?php
            $zoomClasses = '';
            if ($helpZoom->useCloudZoom() == false)
                $zoomClasses .= ' simple-mode';
            else
            {
                if ($helpZoom->isPositionInside())
                    $zoomClasses .= ' zoom-inside';
            }
        ?>

        <p class="product-image<?php echo $zoomClasses; ?>" style="max-width: <?php echo $imgWidth; ?>px;" id="p_image">

            <a href="<?php echo $helpImg->getImg($_product, $bigImageWidth, $bigImageHeight); ?>" class="cloud-zoom" id="zoom1" rel="<?php echo $helpZoom->getCloudZoomOptions(); ?>">
                <img id="tatvazoom" src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight); ?>" alt="<?php echo $this->escapeHtml($this->getImageLabel());?>" title="<?php echo $this->escapeHtml($this->getImageLabel());?>" />
            </a>

            <?php if($helpZoom->useLightbox()): ?>
                <?php
                    $zoomBtnClasses = '';
                    if ($helpZoom->useCloudZoom() == false)
                        $zoomBtnClasses .= ' zoom-btn-large';
                    else
                        $zoomBtnClasses .= ' zoom-btn-small';
                ?>
                <a id="zoom-btn" class="lightbox-group<?php echo $zoomBtnClasses; ?>" href="<?php echo $helpImg->getImg($_product, $bigImageWidth, $bigImageHeight); ?>" title="<?php echo $this->getImageLabel(); ?>"><?php echo $this->__('Zoom'); ?></a>

            <?php endif; ?>
        </p>

    <?php else: //Module disabled. Show images in Magento default style ?>

        <p class="product-image" id="p_image"  style="max-width: <?php echo $imgWidth; ?>px;">
            <img id="tatvazoom" src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight); ?>" alt="<?php echo $this->escapeHtml($this->getImageLabel());?>" title="<?php echo $this->escapeHtml($this->getImageLabel());?>" />
        </p>

    <?php endif; ?>

<?php /* ?>
<?php else: //No image ?>
        <p class="product-image" id="p_image" style="max-width: <?php echo $imgWidth; ?>px;">
            <?php
                $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($imgWidth).'" alt="'.$this->escapeHtml($this->getImageLabel()).'" title="'.$this->escapeHtml($this->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </p>
<?php endif; ?>
<?php
     <div id="option-title"></div>
      <div id="video_div" style="display:none;">
					  <object height="363" width="363" type="application/x-shockwave-flash" id="media_player_0" data="<?php echo $video->getvideo_url(); ?>"&amp;enablejsapi=1&amp;playerapiid=dmplayer&amp;autoPlay=1&amp;colors=background:A8BD2D;glow:FFFFFF;special:FF6600;foreground:FFFFFF;ctrl_btn_fgrd_down:FF6600;ctrl_btn_fgrd_over:FF6600;"><param name="allowScriptAccess" value="always"><param name="allowfullscreen" value="true"></object>
					</div>
                           */ ?>      

<?php //Thumbnails ?>

<?php
    //Other settings for thumbnails
    $galleryImages = $this->getGalleryImages();
    $option_image=array();
    $option_image[]=Mage::getModel("advice/advice")->getBundleSimpleImages($_product->getEntityId());

    if($_product->getTypeId()=='bundle')
    {
      $imageCount = count($galleryImages)+ count($option_image[0]) + count($this->getVideos()->getData());
    }
    else
    {
       $imageCount = count($galleryImages)+ count($this->getVideos()->getData());
    }
    $useSlider = false;
?>
<?php if ($imageCount > 0): ?>
    <?php
        $sliderId = "itemslider-zoom";
        $sliderClasses = '';
        $sliderWrapperClasses = '';
        $itemWidthStyle = '';
        $lazy = false;
        $useSlider = $helpZoom->getCfg('thumbnails/slider');

        if (!$useSlider)
        {
            //Add class indicating there's no slider
            $sliderClasses .= ' show-all auto-adjust-width';

            //Number of thumbnails displayed in a single row if slider is not enabled
            //$num = $helpZoom->getCfg('thumbnails/show_items');
            //$widthPercent = round(100 / $num, 4);
            //$itemWidthStyle = 'style="width: ' . $widthPercent . '%;"';
        }
        else //Get slider parameters
        {
            //Add class indicating that there is a slider
            $sliderClasses .= ' slides';
            $sliderWrapperClasses .= ' itemslider-thumbnails';

            //Responsive mode on/off
            $isResponsive = true;

            //Assign number of items in a row to specific viewport width
            /*$breakpoints = trim($helpZoom->getCfg('thumbnails/breakpoints'));
            $showItems = 0;         //Number of items in a row displayed if responsive mode is off
            if (!$breakpoints)
            {
                //Set default value
                $breakpoints = '[0, 2], [240, 3], [320, 4], [480, 5], [768, 3], [1280, 4]';
            }
            elseif (strpos($breakpoints, '[') === false) //Square bracket was not found, no breakpoints specified
            {
                //Responsive mode is off, show static number of items (convert value to int)
                $isResponsive = false;
                $showItems = intval($breakpoints);
            }*/

            //Slider timeout. Set to enable automatic scrolling.
            $timeout = intval($helpZoom->getCfg('thumbnails/timeout'));

            //Scrolling speed
            $speed = intval($helpZoom->getCfg('thumbnails/speed'));

            //If set, slider will loop
            $loop = $helpZoom->getCfg('thumbnails/loop');

            //Number of items that should move on scrolling
            $move = intval($helpZoom->getCfg('thumbnails/move'));
            if ($move > 1)
            {
                //If set value which is not allowed (greater than 1), then set the default value
                $move = 1;
            }

            //Lazy loading
            $lazy = $helpZoom->getCfg('thumbnails/lazy');
        }

        //Modify thumbnail slider depending on number of thumbnails
        if ($imageCount <= 5)
        {
            $sliderWrapperClasses .= " count-{$imageCount}";
        }
        else
        {
            $sliderWrapperClasses .= ' count-multi';
        }

        //Assign number of items in a row to specific viewport width
        if ($imageCount >= 5)
        {
                    $breakpoints = '[0, 1], [219, 2], [299, 3], [459, 4], [640, 5], [747, 3], [1259, 4]'; //All breakpoints -21px
        }
        else
        {
            switch ($imageCount) {
                case 4:
                    $breakpoints = '[0, 1], [219, 2], [299, 3], [459, 4],           [747, 3], [1259, 4]';
                    break;
                case 3:
                    $breakpoints = '[0, 1], [219, 2], [299, 3]';
                    break;
                case 2:
                    $breakpoints = '[0, 1], [219, 2]';
                    break;
                case 1:
                    $breakpoints = '[0, 1]';
                    break;
            }
        }

    ?>
    <div class="more-images slider-arrows3<?php echo $sliderWrapperClasses; ?>">
        <div id="<?php echo $sliderId; ?>" class="thumbnails<?php if($sliderClasses) echo $sliderClasses; ?>">

        <?php //Display thumbnails with cloud zoom or lightbox ?>
         <!-- video code start -->


        <?php if ($helpZoom->isCloudZoomEnabled()): ?>

            <?php foreach ($galleryImages as $_image): ?>
                <?php //Skip, if no image
                    if ($_image->getFile() == NULL)
                        continue; ?>
                <div class="item"<?php echo " {$itemWidthStyle}"; ?>>
                    <a href="<?php echo $helpImg->getImg($_product, $bigImageWidth, $bigImageHeight, 'image', $_image->getFile()); ?>" class="cloud-zoom-gallery lightbox-group" title="<?php echo $this->escapeHtml($_image->getLabel()); ?>"
                        rel="useZoom:'zoom1', smallImage: '<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'image', $_image->getFile()); ?>'" onclick="removevideo('<?php echo $_image->getLabel(); ?>')">
                        <?php if ($lazy): ?>
                            <img class="lazyOwl" data-src="<?php echo $helpImg->getImg($_product, $thumbImgWidth, $thumbImgHeight, 'thumbnail', $_image->getFile()); ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()); ?>" />
                        <?php else: ?>
                            <img src="<?php echo $helpImg->getImg($_product, $thumbImgWidth, $thumbImgHeight, 'thumbnail', $_image->getFile()); ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()); ?>"/>
                        <?php endif; ?>
                    </a>
                </div>
            <?php endforeach; ?>

        <?php else: //Show thumbnails in Magento default style, without cloud zoom and lightbox ?>

            <?php foreach ($galleryImages as $_image): ?>
                <?php //Skip, if no image
                    if ($_image->getFile() == NULL)
                        continue; ?>
                <div class="item"<?php echo " {$itemWidthStyle}"; ?>>
                    <a href="#" onclick="popWin('<?php echo $this->getGalleryUrl($_image) ?>', 'gallery', 'width=300,height=300,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>">
                        <img src="<?php echo $helpImg->getImg($_product, $thumbImgWidth, $thumbImgHeight, 'thumbnail', $_image->getFile()); ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>"/>
                    </a>
                </div>
            <?php endforeach; ?>

        <?php endif; ?>

        <?php if($_product->getTypeId()=='bundle'): ?>



                <?php foreach($option_image[0] as $o_images): ?>
                    <?php foreach($o_images as $o_image): ?>

                       <a href="<?php echo $helpImg->getImg($_product, $bigImageWidth, $bigImageHeight, 'image', $o_image['image']); ?>" class="cloud-zoom-gallery lightbox-group" title="<?php echo $this->escapeHtml($o_image['title']); ?>"
                        rel="useZoom:'zoom1', smallImage: '<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'image', $o_image['image']); ?>'" onclick="removevideo('<?php echo $o_image['title']; ?>')">
                        <?php if ($lazy): ?>
                            <img class="lazyOwl" data-src="<?php echo $helpImg->getImg($_product, $thumbImgWidth, $thumbImgHeight, 'thumbnail', $o_image['image']); ?>" alt="<?php echo $this->escapeHtml($o_image['title']); ?>" />
                        <?php else: ?>
                            <img src="<?php echo $helpImg->getImg($_product, $thumbImgWidth, $thumbImgHeight, 'thumbnail', $o_image['image']); ?>" alt="<?php echo $this->escapeHtml($o_image['title']); ?>"/>
                        <?php endif; ?>
                    </a>
                  <?php endforeach; ?>
                <?php endforeach; ?>
        <?php endif; ?>


           <?php
          $i = 1;
          foreach($this->getVideos() as $_video):  ?>
              <div class="vignettes-fiche-produit" style="margin-left:10px; padding-top:12px">
          <a <?php if($i%4==0): echo "class='last' "; endif;?> href="javascript:"  onclick="displayvideo('<?php echo $_video->getvideo_url();?>')" >
             <?php
                parse_str( parse_url( $_video->getvideo_url(), PHP_URL_QUERY ) );
             ?>
             <span style="background-color:#000;  display:block; text-align:center; height:6px; width:56px"> <img alt="" src="<?php echo $this->getSkinUrl('images/video_bar.gif'); ?>" style="float:none;"  width="56px" height="6px">   </span>

             <img src="http://img.youtube.com/vi/<?php echo $v;?>/2.jpg" width="56" height="44"  />
             <span style="background-color:#000;  display:block; text-align:center; height:6px;width:56px"> <img alt="" src="<?php echo $this->getSkinUrl('images/video_bar.gif'); ?>"  style="float:none;" width="56px" height="6px">   </span>
          </a>
           </div>
        <?php
        $i++;
        endforeach; ?>
        </div>
    </div> <!-- end: more-images -->
<?php endif; //end: $imageCount > 0 ?>
</div> <!-- end: img-box -->



<?php echo $this->getChildHtml('lightboxConfig'); ?>

<script type="text/javascript">
//<![CDATA[

    jQuery(function($) {
        $('#wrap').hover(function () {
          var temp=$('#zoom-btn').attr("href");
          jQuery('#cloud-zoom-big').css('background-image','url('+ temp +')');
          });
        var t; $(window).resize(function() { clearTimeout(t); t = setTimeout(function() { $(".more-images .cloud-zoom-gallery").first().click(); }, 200); });

    <?php if ($useSlider): ?>
        var owl = $('#<?php echo $sliderId; ?>');
        owl.owlCarousel({

            mouseDrag: false,

        <?php if ($lazy): ?>
            lazyLoad: true,
        <?php endif; ?>

        <?php if(!$isResponsive): ?>
            responsive: false,
            items: <?php echo $showItems; ?>,
        <?php else: ?>
            itemsCustom: [ <?php echo $breakpoints; ?> ],
            responsiveRefreshRate: 50,
        <?php endif; ?>

        <?php if ($speed): ?>
            slideSpeed: <?php echo $speed; ?>,
        <?php endif; ?>

        <?php if ($move !== 1): ?>
            scrollPerPage: true,
        <?php endif; ?>

        <?php if ($timeout): ?>
            autoPlay: <?php echo $timeout; ?>,
        <?php endif; ?>

            stopOnHover: true,

        <?php if ($loop): ?>
            rewindNav: true,
            rewindSpeed: 600,
        <?php else: ?>
            rewindNav: false,
        <?php endif; ?>

            pagination: false,
            navigation: true

        }); //end: owl
    <?php endif; ?>

    });
//]]>
</script>

<script type="text/javascript">
function displayvideo(video_url)
{
       if( video_url.indexOf("http://www.youtube.com")>=0)
    {
        if(video_url.indexOf("watch?v=")>=0)
            video_url=video_url.replace("watch?v=","v/");
    }
document.getElementById('video_div').style.display = "block";

document.getElementById('video_div').innerHTML = '<object height="363" width="363" type="application/x-shockwave-flash" id="media_player_0" data="'+video_url+'&amp;autoplay=1"><param name="allowScriptAccess" value="always"><param name="allowfullscreen" value="true"></object>';

document.getElementById('p_image').style.display = 'none';
if(document.getElementById('span_percentage'))
{
  document.getElementById("span_percentage").style.display = "none";
}
if(document.getElementById('span_promo_sub'))
{
  document.getElementById("span_promo_sub").style.display = "none";
}

if(document.getElementById('span_new'))
{
  document.getElementById("span_new").style.display = "none";
}



}



function removevideo(title)
{

    if(title!="")
    {
                    if(title.length>35)
                        title=title.substr(0,35)+"...";
            document.getElementById("option-title").innerHTML='<div style="font-size:12px;padding:0 0 2px 0px; float: left;width: 100%;position: relative;bottom: 0px;color: white;margin:0px 0px 10px 0px; background-color: #555555; text-align:left;">&nbsp;'+title+'</div>';
    document.getElementById('p_image').style.display = 'block';
    document.getElementById('video_div').style.display = 'none';
    document.getElementById('tatvazoom').title=title;
    }
    else
    {
      document.getElementById("option-title").innerHTML='';
      document.getElementById('p_image').style.display = 'block';
      document.getElementById('video_div').style.display = 'none';


    }


}

</script>
