<?php
/**
 * WDCA - Sweet Tooth
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the WDCA SWEET TOOTH POINTS AND REWARDS 
 * License, which extends the Open Software License (OSL 3.0).
 * The Sweet Tooth License is available at this URL: 
 *      http://www.wdca.ca/solutions_page_sweettooth/Sweet_Tooth_License.php
 * The Open Software License is available at this URL: 
 *      http://opensource.org/licenses/osl-3.0.php
 * 
 * DISCLAIMER
 * 
 * By adding to, editing, or in any way modifying this code, WDCA is 
 * not held liable for any inconsistencies or abnormalities in the 
 * behaviour of this code. 
 * By adding to, editing, or in any way modifying this code, the Licensee
 * terminates any agreement of support offered by WDCA, outlined in the 
 * provided Sweet Tooth License.
 * Upon discovery of modified code in the process of support, the Licensee
 * is still held accountable for any and all billable time WDCA spent
 * during the support process.
 * WDCA does not guarantee compatibility with any other framework extension.
 * WDCA is not responsbile for any inconsistencies or abnormalities in the
 * behaviour of this code if caused by other framework extension.
 * If you did not receive a copy of the license, please send an email to
 * contact@wdca.ca or call 1-888-699-WDCA(9322), so we can send you a copy
 * immediately.
 *
 * @category   [TBT]
 * @package    [TBT_Rewards]
 * @copyright  Copyright (c) 2009 Web Development Canada (http://www.wdca.ca)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * Checkout Reward Earned
 *
 * @category   TBT
 * @package    TBT_Rewards
 * @author     WDCA Sweet Tooth Team <contact@wdca.ca>
 */
?>
<!--<?php
$shouldWarnGuest = $this->getShowWarningTextMessage();
?>
<?php if ($this->showEarnings()): ?>
    <tr>
        <td class="a-right cart-points-total_earned" colspan="<?php echo $this->getColspan(); ?>">
            <div class="caption"><?php echo $this->__('You Will Earn:') ?></div>
        </td>
        <td style="" class="a-right cart-points-total_earned">
            <span class="price">
                <?php echo $this->getPointsEarned() ?>
            </span>
        </td>
    </tr>

<?php if($shouldWarnGuest): ?>
    <tr>
        <td colspan="<?php echo $this->getColspan()+1; ?>">
            <div class="guest-rewards-warning-message">
            <?php if ($this->hasDistributions() && $this->hasRedemptions()): ?>
                <?php echo $this->__('Please create an account or log-in to claim your earnings and spend your points.'); ?>
            <?php elseif($this->hasDistributions()): ?>
                <?php echo $this->__('Please create an account or log-in to claim your earnings.'); ?>
            <?php elseif($this->hasRedemptions()): ?>
                <?php echo $this->__('Please create an account or log-in to spend your points.'); ?>
            <?php else: ?>
		    <?php /* No msg to display */ ?>
            <?php endif; ?>
            </div>
        </td>
    </tr>
<?php endif; ?>

<?php endif; ?>-->

<?php
$shouldWarnGuest = $this->getShowWarningTextMessage();
?>
<?php if ($this->showEarnings()): ?>

            <?php echo $this->__('Reward points earned:') ?>
            <span><?php echo $this->getPointsEarned() ?></span>

<?php if($shouldWarnGuest): ?>
            <div class="guest-rewards-warning-message">
            <?php if ($this->hasDistributions() && $this->hasRedemptions()): ?>
                <?php echo $this->__('Please Create an account or log-in to enjoy our Reward Program.'); ?> <a id="cartpopup" href="#" onclick="return afficherPopin('popinproductalert')"><?php echo $this->__('Learn more about it.'); ?></a>
            <?php elseif($this->hasDistributions()): ?>
               <?php echo $this->__('Please Create an account or log-in to enjoy our Reward Program.'); ?> <a id="cartpopup" href="#" onclick="return afficherPopin('popinproductalert')"><?php echo $this->__('Learn more about it.'); ?></a>
            <?php elseif($this->hasRedemptions()): ?>
                <?php echo $this->__('Please create an account or log-in to spend your points.'); ?>
            <?php else: ?>
		    <?php /* No msg to display */ ?>
            <?php endif; ?>
            </div>

<?php endif; ?>

<?php endif; ?>

